// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/transfers/transfers.proto

package transfers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type WalletResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	AvailableMinor int64                  `protobuf:"varint,4,opt,name=available_minor,json=availableMinor,proto3" json:"available_minor,omitempty"`
	ReservedMinor  int64                  `protobuf:"varint,5,opt,name=reserved_minor,json=reservedMinor,proto3" json:"reserved_minor,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{1}
}

func (x *WalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WalletResponse) GetAvailableMinor() int64 {
	if x != nil {
		return x.AvailableMinor
	}
	return 0
}

func (x *WalletResponse) GetReservedMinor() int64 {
	if x != nil {
		return x.ReservedMinor
	}
	return 0
}

func (x *WalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransferRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{3}
}

func (x *TransferResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *TransferResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ProvisionCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCustomerRequest) Reset() {
	*x = ProvisionCustomerRequest{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCustomerRequest) ProtoMessage() {}

func (x *ProvisionCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCustomerRequest.ProtoReflect.Descriptor instead.
func (*ProvisionCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionCustomerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProvisionCustomerRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ProvisionCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	BankName      string                 `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankCode      string                 `protobuf:"bytes,5,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCustomerResponse) Reset() {
	*x = ProvisionCustomerResponse{}
	mi := &file_proto_transfers_transfers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCustomerResponse) ProtoMessage() {}

func (x *ProvisionCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfers_transfers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCustomerResponse.ProtoReflect.Descriptor instead.
func (*ProvisionCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfers_transfers_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionCustomerResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ProvisionCustomerResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ProvisionCustomerResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *ProvisionCustomerResponse) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *ProvisionCustomerResponse) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *ProvisionCustomerResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_transfers_transfers_proto protoreflect.FileDescriptor

const file_proto_transfers_transfers_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/transfers/transfers.proto\x12\x12nabla.transfers.v1\"G\n" +
	"\x10GetWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xca\x01\n" +
	"\x0eWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0favailable_minor\x18\x04 \x01(\x03R\x0eavailableMinor\x12%\n" +
	"\x0ereserved_minor\x18\x05 \x01(\x03R\rreservedMinor\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"N\n" +
	"\x12GetTransferRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\"\xa8\x01\n" +
	"\x10TransferResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"O\n" +
	"\x18ProvisionCustomerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xd8\x01\n" +
	"\x19ProvisionCustomerResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1b\n" +
	"\tbank_name\x18\x04 \x01(\tR\bbankName\x12\x1b\n" +
	"\tbank_code\x18\x05 \x01(\tR\bbankCode\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency2\xb8\x02\n" +
	"\x10TransfersService\x12U\n" +
	"\tGetWallet\x12$.nabla.transfers.v1.GetWalletRequest\x1a\".nabla.transfers.v1.WalletResponse\x12[\n" +
	"\vGetTransfer\x12&.nabla.transfers.v1.GetTransferRequest\x1a$.nabla.transfers.v1.TransferResponse\x12p\n" +
	"\x11ProvisionCustomer\x12,.nabla.transfers.v1.ProvisionCustomerRequest\x1a-.nabla.transfers.v1.ProvisionCustomerResponseB/Z-nabla/transfers-svc/proto/transfers;transfersb\x06proto3"

var (
	file_proto_transfers_transfers_proto_rawDescOnce sync.Once
	file_proto_transfers_transfers_proto_rawDescData []byte
)

func file_proto_transfers_transfers_proto_rawDescGZIP() []byte {
	file_proto_transfers_transfers_proto_rawDescOnce.Do(func() {
		file_proto_transfers_transfers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transfers_transfers_proto_rawDesc), len(file_proto_transfers_transfers_proto_rawDesc)))
	})
	return file_proto_transfers_transfers_proto_rawDescData
}

var file_proto_transfers_transfers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_transfers_transfers_proto_goTypes = []any{
	(*GetWalletRequest)(nil),          // 0: nabla.transfers.v1.GetWalletRequest
	(*WalletResponse)(nil),            // 1: nabla.transfers.v1.WalletResponse
	(*GetTransferRequest)(nil),        // 2: nabla.transfers.v1.GetTransferRequest
	(*TransferResponse)(nil),          // 3: nabla.transfers.v1.TransferResponse
	(*ProvisionCustomerRequest)(nil),  // 4: nabla.transfers.v1.ProvisionCustomerRequest
	(*ProvisionCustomerResponse)(nil), // 5: nabla.transfers.v1.ProvisionCustomerResponse
}
var file_proto_transfers_transfers_proto_depIdxs = []int32{
	0, // 0: nabla.transfers.v1.TransfersService.GetWallet:input_type -> nabla.transfers.v1.GetWalletRequest
	2, // 1: nabla.transfers.v1.TransfersService.GetTransfer:input_type -> nabla.transfers.v1.GetTransferRequest
	4, // 2: nabla.transfers.v1.TransfersService.ProvisionCustomer:input_type -> nabla.transfers.v1.ProvisionCustomerRequest
	1, // 3: nabla.transfers.v1.TransfersService.GetWallet:output_type -> nabla.transfers.v1.WalletResponse
	3, // 4: nabla.transfers.v1.TransfersService.GetTransfer:output_type -> nabla.transfers.v1.TransferResponse
	5, // 5: nabla.transfers.v1.TransfersService.ProvisionCustomer:output_type -> nabla.transfers.v1.ProvisionCustomerResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_transfers_transfers_proto_init() }
func file_proto_transfers_transfers_proto_init() {
	if File_proto_transfers_transfers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transfers_transfers_proto_rawDesc), len(file_proto_transfers_transfers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transfers_transfers_proto_goTypes,
		DependencyIndexes: file_proto_transfers_transfers_proto_depIdxs,
		MessageInfos:      file_proto_transfers_transfers_proto_msgTypes,
	}.Build()
	File_proto_transfers_transfers_proto = out.File
	file_proto_transfers_transfers_proto_goTypes = nil
	file_proto_transfers_transfers_proto_depIdxs = nil
}
