// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/transfers/transfers.proto

package transfers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransfersService_GetWallet_FullMethodName         = "/nabla.transfers.v1.TransfersService/GetWallet"
	TransfersService_GetTransfer_FullMethodName       = "/nabla.transfers.v1.TransfersService/GetTransfer"
	TransfersService_ProvisionCustomer_FullMethodName = "/nabla.transfers.v1.TransfersService/ProvisionCustomer"
)

// TransfersServiceClient is the client API for TransfersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransfersServiceClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	ProvisionCustomer(ctx context.Context, in *ProvisionCustomerRequest, opts ...grpc.CallOption) (*ProvisionCustomerResponse, error)
}

type transfersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransfersServiceClient(cc grpc.ClientConnInterface) TransfersServiceClient {
	return &transfersServiceClient{cc}
}

func (c *transfersServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, TransfersService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transfersServiceClient) GetTransfer(ctx context.Context, in *GetTransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, TransfersService_GetTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transfersServiceClient) ProvisionCustomer(ctx context.Context, in *ProvisionCustomerRequest, opts ...grpc.CallOption) (*ProvisionCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionCustomerResponse)
	err := c.cc.Invoke(ctx, TransfersService_ProvisionCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransfersServiceServer is the server API for TransfersService service.
// All implementations must embed UnimplementedTransfersServiceServer
// for forward compatibility.
type TransfersServiceServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*WalletResponse, error)
	GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error)
	ProvisionCustomer(context.Context, *ProvisionCustomerRequest) (*ProvisionCustomerResponse, error)
	mustEmbedUnimplementedTransfersServiceServer()
}

// UnimplementedTransfersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransfersServiceServer struct{}

func (UnimplementedTransfersServiceServer) GetWallet(context.Context, *GetWalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedTransfersServiceServer) GetTransfer(context.Context, *GetTransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedTransfersServiceServer) ProvisionCustomer(context.Context, *ProvisionCustomerRequest) (*ProvisionCustomerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionCustomer not implemented")
}
func (UnimplementedTransfersServiceServer) mustEmbedUnimplementedTransfersServiceServer() {}
func (UnimplementedTransfersServiceServer) testEmbeddedByValue()                          {}

// UnsafeTransfersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransfersServiceServer will
// result in compilation errors.
type UnsafeTransfersServiceServer interface {
	mustEmbedUnimplementedTransfersServiceServer()
}

func RegisterTransfersServiceServer(s grpc.ServiceRegistrar, srv TransfersServiceServer) {
	// If the following call panics, it indicates UnimplementedTransfersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransfersService_ServiceDesc, srv)
}

func _TransfersService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransfersServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransfersService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransfersServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransfersService_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransfersServiceServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransfersService_GetTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransfersServiceServer).GetTransfer(ctx, req.(*GetTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransfersService_ProvisionCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransfersServiceServer).ProvisionCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransfersService_ProvisionCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransfersServiceServer).ProvisionCustomer(ctx, req.(*ProvisionCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransfersService_ServiceDesc is the grpc.ServiceDesc for TransfersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransfersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nabla.transfers.v1.TransfersService",
	HandlerType: (*TransfersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _TransfersService_GetWallet_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _TransfersService_GetTransfer_Handler,
		},
		{
			MethodName: "ProvisionCustomer",
			Handler:    _TransfersService_ProvisionCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transfers/transfers.proto",
}
