// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: killswitch.sql

package transfersdb

import (
	"context"

	"github.com/google/uuid"
)

const countLedgerTransactions = `-- name: CountLedgerTransactions :one
SELECT count(*)::bigint FROM ledger_transactions
`

// CountLedgerTransactions reports how many ledger transactions the proof scanned,
// so a clean proof records the size of what it verified rather than just "no
// breaks found".
func (q *Queries) CountLedgerTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerTransactions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const featureFlagEnabled = `-- name: FeatureFlagEnabled :one

SELECT enabled FROM feature_flags WHERE key = $1
`

// Queries behind the payments kill switch and the balance proof that can trip it.
// The kill switch is a single row in feature_flags; the balance proof reads the
// ledger and reports the two invariants that, if broken, mean money is unaccounted
// for: a ledger transaction that does not net to zero, and a customer account that
// has gone negative without permission.
// FeatureFlagEnabled reads one flag. NoRows (an absent row) is not an error: the
// caller reads it as "flag unset" and applies the flag's documented default.
func (q *Queries) FeatureFlagEnabled(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, featureFlagEnabled, key)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const negativeLedgerAccounts = `-- name: NegativeLedgerAccounts :many
SELECT id, account_type, currency, balance_minor
FROM ledger_accounts
WHERE balance_minor < 0 AND allows_negative = false
LIMIT $1
`

type NegativeLedgerAccountsRow struct {
	ID           uuid.UUID `json:"id"`
	AccountType  string    `json:"account_type"`
	Currency     string    `json:"currency"`
	BalanceMinor int64     `json:"balance_minor"`
}

// NegativeLedgerAccounts lists customer accounts that have gone below zero without
// being permitted to (allows_negative marks the few system accounts, e.g. a
// settlement clearing account, that legitimately carry a negative balance). A
// non-empty result means an account was debited past its funds.
func (q *Queries) NegativeLedgerAccounts(ctx context.Context, limit int32) ([]NegativeLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, negativeLedgerAccounts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NegativeLedgerAccountsRow
	for rows.Next() {
		var i NegativeLedgerAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountType,
			&i.Currency,
			&i.BalanceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeatureFlag = `-- name: SetFeatureFlag :exec
INSERT INTO feature_flags (key, enabled, note, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
  SET enabled = EXCLUDED.enabled, note = EXCLUDED.note, updated_at = now()
`

type SetFeatureFlagParams struct {
	Key     string `json:"key"`
	Enabled bool   `json:"enabled"`
	Note    string `json:"note"`
}

// SetFeatureFlag is the single writer of a flag: it upserts so flipping a switch
// that was never set and re-flipping one that was are the same operation, and
// stamps updated_at + the human-readable note recording why.
func (q *Queries) SetFeatureFlag(ctx context.Context, arg SetFeatureFlagParams) error {
	_, err := q.db.Exec(ctx, setFeatureFlag, arg.Key, arg.Enabled, arg.Note)
	return err
}

const unbalancedLedgerTransactions = `-- name: UnbalancedLedgerTransactions :many
SELECT le.transaction_id,
       le.currency,
       sum(CASE WHEN le.entry_type = 'credit' THEN le.amount_minor ELSE -le.amount_minor END)::bigint AS net_minor
FROM ledger_entries le
GROUP BY le.transaction_id, le.currency
HAVING sum(CASE WHEN le.entry_type = 'credit' THEN le.amount_minor ELSE -le.amount_minor END) <> 0
LIMIT $1
`

type UnbalancedLedgerTransactionsRow struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	Currency      string    `json:"currency"`
	NetMinor      int64     `json:"net_minor"`
}

// UnbalancedLedgerTransactions lists any ledger transaction whose entries do not
// net to zero within a currency. Double-entry means every transaction — posted or
// reversed — must balance on its own, so this is checked across all of them, not
// just posted ones. A non-empty result is a hard integrity break. LIMIT bounds the
// output: existence and a few examples are all the proof needs.
func (q *Queries) UnbalancedLedgerTransactions(ctx context.Context, limit int32) ([]UnbalancedLedgerTransactionsRow, error) {
	rows, err := q.db.Query(ctx, unbalancedLedgerTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnbalancedLedgerTransactionsRow
	for rows.Next() {
		var i UnbalancedLedgerTransactionsRow
		if err := rows.Scan(&i.TransactionID, &i.Currency, &i.NetMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
