// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package transfersdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bank struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	NonInterest bool        `json:"non_interest"`
	IsActive    bool        `json:"is_active"`
	NovacCode   pgtype.Text `json:"novac_code"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Beneficiary struct {
	ID                      uuid.UUID          `json:"id"`
	UserID                  uuid.UUID          `json:"user_id"`
	Type                    string             `json:"type"`
	RecipientUserID         pgtype.UUID        `json:"recipient_user_id"`
	BankCode                pgtype.Text        `json:"bank_code"`
	BankName                pgtype.Text        `json:"bank_name"`
	AccountName             string             `json:"account_name"`
	Currency                string             `json:"currency"`
	AccountNumberCiphertext []byte             `json:"account_number_ciphertext"`
	AccountNumberLast4      pgtype.Text        `json:"account_number_last4"`
	AccountNumberBlindIndex []byte             `json:"account_number_blind_index"`
	KeyVersion              pgtype.Int2        `json:"key_version"`
	VerificationStatus      string             `json:"verification_status"`
	VerifiedName            pgtype.Text        `json:"verified_name"`
	VerifiedAt              pgtype.Timestamptz `json:"verified_at"`
	VerificationProvider    pgtype.Text        `json:"verification_provider"`
	Nickname                pgtype.Text        `json:"nickname"`
	IsFavourite             bool               `json:"is_favourite"`
	IsSaved                 bool               `json:"is_saved"`
	CoolingPeriodEndsAt     pgtype.Timestamptz `json:"cooling_period_ends_at"`
	LastUsedAt              pgtype.Timestamptz `json:"last_used_at"`
	UseCount                int32              `json:"use_count"`
	Status                  string             `json:"status"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
	RecipientAccountNumber  pgtype.Text        `json:"recipient_account_number"`
	RecipientUsername       pgtype.Text        `json:"recipient_username"`
	RecipientAvatarUrl      pgtype.Text        `json:"recipient_avatar_url"`
}

type CustomerLimit struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	LimitType     string             `json:"limit_type"`
	Currency      string             `json:"currency"`
	AmountMinor   pgtype.Int8        `json:"amount_minor"`
	CountLimit    pgtype.Int4        `json:"count_limit"`
	Source        string             `json:"source"`
	Reason        pgtype.Text        `json:"reason"`
	EffectiveFrom time.Time          `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	CreatedAt     time.Time          `json:"created_at"`
}

type FeatureFlag struct {
	Key       string    `json:"key"`
	Enabled   bool      `json:"enabled"`
	Note      string    `json:"note"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Hold struct {
	ID          uuid.UUID          `json:"id"`
	WalletID    uuid.UUID          `json:"wallet_id"`
	TransferID  pgtype.UUID        `json:"transfer_id"`
	AmountMinor int64              `json:"amount_minor"`
	Status      string             `json:"status"`
	ExpiresAt   time.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type LedgerAccount struct {
	ID             uuid.UUID   `json:"id"`
	AccountType    string      `json:"account_type"`
	Currency       string      `json:"currency"`
	OwnerType      string      `json:"owner_type"`
	CustomerID     pgtype.UUID `json:"customer_id"`
	ProviderName   pgtype.Text `json:"provider_name"`
	Name           string      `json:"name"`
	Code           string      `json:"code"`
	BalanceMinor   int64       `json:"balance_minor"`
	ReservedMinor  int64       `json:"reserved_minor"`
	PendingMinor   int64       `json:"pending_minor"`
	AvailableMinor int64       `json:"available_minor"`
	AllowsNegative bool        `json:"allows_negative"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type LedgerEntry struct {
	ID                uuid.UUID   `json:"id"`
	TransactionID     uuid.UUID   `json:"transaction_id"`
	WalletID          pgtype.UUID `json:"wallet_id"`
	EntryType         pgtype.Text `json:"entry_type"`
	AccountID         pgtype.UUID `json:"account_id"`
	Direction         pgtype.Text `json:"direction"`
	AmountMinor       int64       `json:"amount_minor"`
	Currency          string      `json:"currency"`
	BalanceAfterMinor pgtype.Int8 `json:"balance_after_minor"`
	Description       pgtype.Text `json:"description"`
	CreatedAt         time.Time   `json:"created_at"`
}

type LedgerTransaction struct {
	ID             uuid.UUID          `json:"id"`
	Reference      string             `json:"reference"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	Description    pgtype.Text        `json:"description"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
	AvailableAt   time.Time          `json:"available_at"`
	CreatedAt     time.Time          `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type PaymentRequest struct {
	ID                uuid.UUID          `json:"id"`
	RequesterUserID   uuid.UUID          `json:"requester_user_id"`
	PayerUserID       uuid.UUID          `json:"payer_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	Note              pgtype.Text        `json:"note"`
	Status            string             `json:"status"`
	TransferID        pgtype.UUID        `json:"transfer_id"`
	RequesterName     pgtype.Text        `json:"requester_name"`
	RequesterUsername pgtype.Text        `json:"requester_username"`
	PayerName         pgtype.Text        `json:"payer_name"`
	PayerUsername     pgtype.Text        `json:"payer_username"`
	DeclineReason     pgtype.Text        `json:"decline_reason"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type ProviderRequest struct {
	ID                uuid.UUID   `json:"id"`
	TransferID        uuid.UUID   `json:"transfer_id"`
	ProviderName      string      `json:"provider_name"`
	ProviderReference pgtype.Text `json:"provider_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	Outcome           string      `json:"outcome"`
	ErrorCode         pgtype.Text `json:"error_code"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	CreatedAt         time.Time   `json:"created_at"`
}

type ProviderWebhook struct {
	ID                 uuid.UUID          `json:"id"`
	ProviderName       string             `json:"provider_name"`
	EventID            string             `json:"event_id"`
	EventType          string             `json:"event_type"`
	RawBodySha256      string             `json:"raw_body_sha256"`
	Payload            []byte             `json:"payload"`
	SignatureValid     bool               `json:"signature_valid"`
	Status             string             `json:"status"`
	ProcessedAt        pgtype.Timestamptz `json:"processed_at"`
	CreatedAt          time.Time          `json:"created_at"`
	ProcessingAttempts int16              `json:"processing_attempts"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	ReplayedFromID     pgtype.UUID        `json:"replayed_from_id"`
	ReplayedBy         pgtype.UUID        `json:"replayed_by"`
}

type ReconciliationItem struct {
	ID                  uuid.UUID          `json:"id"`
	RunID               uuid.UUID          `json:"run_id"`
	MatchStatus         string             `json:"match_status"`
	ProviderReference   pgtype.Text        `json:"provider_reference"`
	OurReference        pgtype.Text        `json:"our_reference"`
	ProviderAmountMinor pgtype.Int8        `json:"provider_amount_minor"`
	ProviderStatus      pgtype.Text        `json:"provider_status"`
	ProviderTimestamp   pgtype.Timestamptz `json:"provider_timestamp"`
	ProviderPayload     []byte             `json:"provider_payload"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	LedgerAmountMinor   pgtype.Int8        `json:"ledger_amount_minor"`
	Currency            pgtype.Text        `json:"currency"`
	VarianceMinor       int64              `json:"variance_minor"`
	ResolutionStatus    pgtype.Text        `json:"resolution_status"`
	ResolutionNote      pgtype.Text        `json:"resolution_note"`
	CreatedAt           time.Time          `json:"created_at"`
}

type ReconciliationRun struct {
	ID                 uuid.UUID          `json:"id"`
	ProviderName       string             `json:"provider_name"`
	ReconciliationType string             `json:"reconciliation_type"`
	PeriodStart        time.Time          `json:"period_start"`
	PeriodEnd          time.Time          `json:"period_end"`
	Currency           string             `json:"currency"`
	Status             string             `json:"status"`
	ProviderItemCount  int32              `json:"provider_item_count"`
	LedgerItemCount    int32              `json:"ledger_item_count"`
	MatchedCount       int32              `json:"matched_count"`
	BreakCount         int32              `json:"break_count"`
	ProviderTotalMinor int64              `json:"provider_total_minor"`
	LedgerTotalMinor   int64              `json:"ledger_total_minor"`
	VarianceMinor      int64              `json:"variance_minor"`
	TriggeredBy        pgtype.UUID        `json:"triggered_by"`
	CreatedAt          time.Time          `json:"created_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type RoundUpAccrual struct {
	ID                  uuid.UUID          `json:"id"`
	CustomerID          uuid.UUID          `json:"customer_id"`
	Currency            string             `json:"currency"`
	RoundUpMultiplier   int16              `json:"round_up_multiplier"`
	AccruedMinor        int64              `json:"accrued_minor"`
	IsActive            bool               `json:"is_active"`
	SweepThresholdMinor int64              `json:"sweep_threshold_minor"`
	LastSweptAt         pgtype.Timestamptz `json:"last_swept_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type RoundUpItem struct {
	ID                  uuid.UUID          `json:"id"`
	AccrualID           uuid.UUID          `json:"accrual_id"`
	WalletTransactionID uuid.UUID          `json:"wallet_transaction_id"`
	SpendAmountMinor    int64              `json:"spend_amount_minor"`
	RoundUpMinor        int64              `json:"round_up_minor"`
	SweptAt             pgtype.Timestamptz `json:"swept_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

type ScheduledPayment struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	SourceWalletID      uuid.UUID          `json:"source_wallet_id"`
	BeneficiaryID       uuid.UUID          `json:"beneficiary_id"`
	PaymentName         string             `json:"payment_name"`
	ScheduleType        string             `json:"schedule_type"`
	Frequency           pgtype.Text        `json:"frequency"`
	DayOfMonth          pgtype.Int2        `json:"day_of_month"`
	DayOfWeek           pgtype.Int2        `json:"day_of_week"`
	AmountMinor         int64              `json:"amount_minor"`
	Currency            string             `json:"currency"`
	Narrative           pgtype.Text        `json:"narrative"`
	NextRunAt           time.Time          `json:"next_run_at"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	EndDate             pgtype.Timestamptz `json:"end_date"`
	MaxOccurrences      pgtype.Int4        `json:"max_occurrences"`
	OccurrenceCount     int32              `json:"occurrence_count"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	Status              string             `json:"status"`
	PauseReason         pgtype.Text        `json:"pause_reason"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type ScheduledPaymentRun struct {
	ID                 uuid.UUID   `json:"id"`
	ScheduledPaymentID uuid.UUID   `json:"scheduled_payment_id"`
	ScheduledFor       time.Time   `json:"scheduled_for"`
	ExecutedAt         time.Time   `json:"executed_at"`
	Outcome            string      `json:"outcome"`
	TransferID         pgtype.UUID `json:"transfer_id"`
	ErrorMessage       pgtype.Text `json:"error_message"`
}

type Transfer struct {
	ID                    uuid.UUID          `json:"id"`
	Reference             string             `json:"reference"`
	SenderUserID          uuid.UUID          `json:"sender_user_id"`
	SourceWalletID        uuid.UUID          `json:"source_wallet_id"`
	BeneficiaryID         uuid.UUID          `json:"beneficiary_id"`
	DestinationWalletID   pgtype.UUID        `json:"destination_wallet_id"`
	Type                  string             `json:"type"`
	SendAmountMinor       int64              `json:"send_amount_minor"`
	SendCurrency          string             `json:"send_currency"`
	ReceiveAmountMinor    int64              `json:"receive_amount_minor"`
	ReceiveCurrency       string             `json:"receive_currency"`
	FeeMinor              int64              `json:"fee_minor"`
	FeeCurrency           pgtype.Text        `json:"fee_currency"`
	TotalDebitMinor       int64              `json:"total_debit_minor"`
	FxQuoteID             pgtype.UUID        `json:"fx_quote_id"`
	Status                string             `json:"status"`
	FailureCode           pgtype.Text        `json:"failure_code"`
	FailureReason         pgtype.Text        `json:"failure_reason"`
	HoldID                pgtype.UUID        `json:"hold_id"`
	LedgerTransactionID   pgtype.UUID        `json:"ledger_transaction_id"`
	ProviderName          pgtype.Text        `json:"provider_name"`
	ProviderReference     pgtype.Text        `json:"provider_reference"`
	SubmittedAt           pgtype.Timestamptz `json:"submitted_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	IdempotencyKey        string             `json:"idempotency_key"`
	Narrative             pgtype.Text        `json:"narrative"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	ReversalTransactionID pgtype.UUID        `json:"reversal_transaction_id"`
	ExpectedSettlementAt  pgtype.Timestamptz `json:"expected_settlement_at"`
}

type TransferEvent struct {
	ID              uuid.UUID   `json:"id"`
	TransferID      uuid.UUID   `json:"transfer_id"`
	FromStatus      pgtype.Text `json:"from_status"`
	ToStatus        string      `json:"to_status"`
	ActorType       string      `json:"actor_type"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	Reason          pgtype.Text `json:"reason"`
	ProviderPayload []byte      `json:"provider_payload"`
	CreatedAt       time.Time   `json:"created_at"`
}

type TransferPinAuthorization struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	AmountMinor         int64              `json:"amount_minor"`
	Currency            string             `json:"currency"`
	RecipientDescriptor string             `json:"recipient_descriptor"`
	CreatedAt           time.Time          `json:"created_at"`
	ExpiresAt           time.Time          `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
}

type TransferQuote struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	SourceWalletID     uuid.UUID   `json:"source_wallet_id"`
	BeneficiaryID      uuid.UUID   `json:"beneficiary_id"`
	Type               string      `json:"type"`
	SendAmountMinor    int64       `json:"send_amount_minor"`
	SendCurrency       string      `json:"send_currency"`
	ReceiveAmountMinor int64       `json:"receive_amount_minor"`
	ReceiveCurrency    string      `json:"receive_currency"`
	FeeMinor           int64       `json:"fee_minor"`
	FeeCurrency        pgtype.Text `json:"fee_currency"`
	TotalDebitMinor    int64       `json:"total_debit_minor"`
	FxQuoteID          pgtype.UUID `json:"fx_quote_id"`
	RateNumerator      pgtype.Int8 `json:"rate_numerator"`
	RateScale          pgtype.Int2 `json:"rate_scale"`
	HighValue          bool        `json:"high_value"`
	HighValueNote      pgtype.Text `json:"high_value_note"`
	Status             string      `json:"status"`
	ExpiresAt          time.Time   `json:"expires_at"`
	CreatedAt          time.Time   `json:"created_at"`
}

type Wallet struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Currency        string      `json:"currency"`
	Status          string      `json:"status"`
	AvailableMinor  int64       `json:"available_minor"`
	ReservedMinor   int64       `json:"reserved_minor"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	LedgerAccountID pgtype.UUID `json:"ledger_account_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	CustomerID      pgtype.UUID `json:"customer_id"`
	Name            pgtype.Text `json:"name"`
	WalletType      string      `json:"wallet_type"`
	IsDefault       bool        `json:"is_default"`
}

type WalletTransaction struct {
	ID                  uuid.UUID   `json:"id"`
	WalletID            pgtype.UUID `json:"wallet_id"`
	CustomerID          uuid.UUID   `json:"customer_id"`
	LedgerTransactionID pgtype.UUID `json:"ledger_transaction_id"`
	Direction           string      `json:"direction"`
	AmountMinor         int64       `json:"amount_minor"`
	Currency            string      `json:"currency"`
	FeeMinor            int64       `json:"fee_minor"`
	BalanceAfterMinor   pgtype.Int8 `json:"balance_after_minor"`
	TransactionType     string      `json:"transaction_type"`
	CounterpartyName    pgtype.Text `json:"counterparty_name"`
	CounterpartyType    pgtype.Text `json:"counterparty_type"`
	CounterpartyID      pgtype.UUID `json:"counterparty_id"`
	Description         pgtype.Text `json:"description"`
	SourceType          pgtype.Text `json:"source_type"`
	SourceID            pgtype.UUID `json:"source_id"`
	OccurredAt          time.Time   `json:"occurred_at"`
	CreatedAt           time.Time   `json:"created_at"`
}
