// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pin_authorizations.sql

package transfersdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePINAuthorization = `-- name: ConsumePINAuthorization :one
UPDATE transfer_pin_authorizations
   SET consumed_at = now()
 WHERE id = $1 AND user_id = $2 AND amount_minor = $3 AND currency = $4
   AND recipient_descriptor = $5 AND consumed_at IS NULL AND expires_at > now()
 RETURNING id, user_id, amount_minor, currency, recipient_descriptor, created_at, expires_at, consumed_at
`

type ConsumePINAuthorizationParams struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	AmountMinor         int64     `json:"amount_minor"`
	Currency            string    `json:"currency"`
	RecipientDescriptor string    `json:"recipient_descriptor"`
}

// Single-use AND bound. Matches only an unconsumed, unexpired token that belongs
// to this user and was minted for exactly this amount, currency and recipient.
// `SET consumed_at = now() ... WHERE consumed_at IS NULL` is the atomic single-shot
// guard — a second attempt (a replay, or two taps of Send) matches no row — and
// binding amount+currency+recipient_descriptor is what stops a token issued for
// one payment being spent on a different one. Run inside the money transaction so
// the consume and the transfer commit or roll back together. pgx.ErrNoRows means
// "no such live token for this exact payment", which the service reads as refuse.
func (q *Queries) ConsumePINAuthorization(ctx context.Context, arg ConsumePINAuthorizationParams) (TransferPinAuthorization, error) {
	row := q.db.QueryRow(ctx, consumePINAuthorization,
		arg.ID,
		arg.UserID,
		arg.AmountMinor,
		arg.Currency,
		arg.RecipientDescriptor,
	)
	var i TransferPinAuthorization
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMinor,
		&i.Currency,
		&i.RecipientDescriptor,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createPINAuthorization = `-- name: CreatePINAuthorization :one
INSERT INTO transfer_pin_authorizations (user_id, amount_minor, currency, recipient_descriptor, expires_at)
VALUES ($1,$2,$3,$4,$5) RETURNING id, user_id, amount_minor, currency, recipient_descriptor, created_at, expires_at, consumed_at
`

type CreatePINAuthorizationParams struct {
	UserID              uuid.UUID `json:"user_id"`
	AmountMinor         int64     `json:"amount_minor"`
	Currency            string    `json:"currency"`
	RecipientDescriptor string    `json:"recipient_descriptor"`
	ExpiresAt           time.Time `json:"expires_at"`
}

// Mints the server-side proof that the payer's PIN was verified on the
// authorize-pin step, bound to the exact amount, currency and recipient the
// confirmation screen showed. RETURNING * so the handler can hand the id and
// expiry back to the client to carry into POST /transfers.
func (q *Queries) CreatePINAuthorization(ctx context.Context, arg CreatePINAuthorizationParams) (TransferPinAuthorization, error) {
	row := q.db.QueryRow(ctx, createPINAuthorization,
		arg.UserID,
		arg.AmountMinor,
		arg.Currency,
		arg.RecipientDescriptor,
		arg.ExpiresAt,
	)
	var i TransferPinAuthorization
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMinor,
		&i.Currency,
		&i.RecipientDescriptor,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
