// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package transfersdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActiveLimit(ctx context.Context, arg ActiveLimitParams) (CustomerLimit, error)
	AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error
	BankBeneficiaryForAccount(ctx context.Context, arg BankBeneficiaryForAccountParams) (Beneficiary, error)
	BankByCode(ctx context.Context, code string) (Bank, error)
	// Duration (seconds) of completed payouts to a bank, newest first, bounded so a
	// busy rail cannot make the timing query grow without limit.
	BankTimingSamples(ctx context.Context, arg BankTimingSamplesParams) ([]BankTimingSamplesRow, error)
	BeneficiaryByID(ctx context.Context, arg BeneficiaryByIDParams) (Beneficiary, error)
	BeneficiaryCiphertext(ctx context.Context, id uuid.UUID) ([]byte, error)
	BeneficiaryInternalByID(ctx context.Context, id uuid.UUID) (Beneficiary, error)
	// Completed transfers to one payee over the last six months, oldest first — the
	// shape /cadence payload for /transfers/suggestions.
	BeneficiaryTransferHistory(ctx context.Context, arg BeneficiaryTransferHistoryParams) ([]BeneficiaryTransferHistoryRow, error)
	CancelSchedule(ctx context.Context, arg CancelScheduleParams) (int64, error)
	CancelTransfer(ctx context.Context, arg CancelTransferParams) (int64, error)
	CaptureHold(ctx context.Context, id uuid.UUID) (int64, error)
	ClaimDueSchedules(ctx context.Context, limit int32) ([]ScheduledPayment, error)
	ClaimOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	// The claim: zero the accrual so a concurrent worker finds nothing to do; the
	// WHERE clause is what makes the race safe (only one winner per accrual).
	ClaimRoundUpAccrual(ctx context.Context, id uuid.UUID) (int64, error)
	CompleteReconciliationRun(ctx context.Context, arg CompleteReconciliationRunParams) error
	CompleteSchedule(ctx context.Context, id uuid.UUID) error
	CompleteTransfer(ctx context.Context, id uuid.UUID) (int64, error)
	CompletedTransfersForReconciliation(ctx context.Context, arg CompletedTransfersForReconciliationParams) ([]CompletedTransfersForReconciliationRow, error)
	// Single-use AND bound. Matches only an unconsumed, unexpired token that belongs
	// to this user and was minted for exactly this amount, currency and recipient.
	// `SET consumed_at = now() ... WHERE consumed_at IS NULL` is the atomic single-shot
	// guard — a second attempt (a replay, or two taps of Send) matches no row — and
	// binding amount+currency+recipient_descriptor is what stops a token issued for
	// one payment being spent on a different one. Run inside the money transaction so
	// the consume and the transfer commit or roll back together. pgx.ErrNoRows means
	// "no such live token for this exact payment", which the service reads as refuse.
	ConsumePINAuthorization(ctx context.Context, arg ConsumePINAuthorizationParams) (TransferPinAuthorization, error)
	ConsumeQuote(ctx context.Context, arg ConsumeQuoteParams) (TransferQuote, error)
	ConsumeWalletReservation(ctx context.Context, arg ConsumeWalletReservationParams) error
	// CountLedgerTransactions reports how many ledger transactions the proof scanned,
	// so a clean proof records the size of what it verified rather than just "no
	// breaks found".
	CountLedgerTransactions(ctx context.Context) (int64, error)
	CreateBeneficiary(ctx context.Context, arg CreateBeneficiaryParams) (Beneficiary, error)
	CreateHold(ctx context.Context, arg CreateHoldParams) (Hold, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	// Mints the server-side proof that the payer's PIN was verified on the
	// authorize-pin step, bound to the exact amount, currency and recipient the
	// confirmation screen showed. RETURNING * so the handler can hand the id and
	// expiry back to the client to carry into POST /transfers.
	CreatePINAuthorization(ctx context.Context, arg CreatePINAuthorizationParams) (TransferPinAuthorization, error)
	CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error)
	CreateProviderRequest(ctx context.Context, arg CreateProviderRequestParams) (ProviderRequest, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (TransferQuote, error)
	CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (ReconciliationRun, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (ScheduledPayment, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error)
	// noinspection SqlResolveForFile
	// noinspection SqlNoDataSourceInspectionForFile
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	// Money in. This is the statement an inbound collection ultimately runs.
	CreditWallet(ctx context.Context, arg CreditWalletParams) error
	DeleteBeneficiary(ctx context.Context, arg DeleteBeneficiaryParams) (int64, error)
	DeleteTierLimit(ctx context.Context, arg DeleteTierLimitParams) error
	DispatchIntentByTransfer(ctx context.Context, arg DispatchIntentByTransferParams) (ProviderRequest, error)
	ExpiredActiveTransferHolds(ctx context.Context, limit int32) ([]ExpiredActiveTransferHoldsRow, error)
	ExtendHold(ctx context.Context, arg ExtendHoldParams) error
	FailScheduleRun(ctx context.Context, arg FailScheduleRunParams) error
	FailTransfer(ctx context.Context, arg FailTransferParams) (int64, error)
	// Queries behind the payments kill switch and the balance proof that can trip it.
	// The kill switch is a single row in feature_flags; the balance proof reads the
	// ledger and reports the two invariants that, if broken, mean money is unaccounted
	// for: a ledger transaction that does not net to zero, and a customer account that
	// has gone negative without permission.
	// FeatureFlagEnabled reads one flag. NoRows (an absent row) is not an error: the
	// caller reads it as "flag unset" and applies the flag's documented default.
	FeatureFlagEnabled(ctx context.Context, key string) (bool, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) (LedgerTransaction, error)
	InsertReconciliationItem(ctx context.Context, arg InsertReconciliationItemParams) error
	InternalBeneficiaryForRecipient(ctx context.Context, arg InternalBeneficiaryForRecipientParams) (Beneficiary, error)
	LimitByUser(ctx context.Context, arg LimitByUserParams) (LimitByUserRow, error)
	ListBanks(ctx context.Context) ([]Bank, error)
	ListBeneficiaries(ctx context.Context, userID uuid.UUID) ([]Beneficiary, error)
	ListProviderWebhooks(ctx context.Context, limit int32) ([]ProviderWebhook, error)
	// The customer's quotes, newest first. Read-only like QuoteByID: listing never
	// consumes a quote. A limit keeps a pathological writer from flooding the
	// screen with hundreds of rows nobody will scroll through.
	ListQuotes(ctx context.Context, arg ListQuotesParams) ([]TransferQuote, error)
	ListReconciliationRuns(ctx context.Context, limit int32) ([]ReconciliationRun, error)
	ListSchedules(ctx context.Context, userID uuid.UUID) ([]ScheduledPayment, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	MarkBeneficiaryUsed(ctx context.Context, id uuid.UUID) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, id uuid.UUID) error
	MarkPaymentRequestPaid(ctx context.Context, arg MarkPaymentRequestPaidParams) (PaymentRequest, error)
	MarkRoundUpItemsSwept(ctx context.Context, accrualID uuid.UUID) error
	MarkWebhookReplayed(ctx context.Context, arg MarkWebhookReplayedParams) error
	// NegativeLedgerAccounts lists customer accounts that have gone below zero without
	// being permitted to (allows_negative marks the few system accounts, e.g. a
	// settlement clearing account, that legitimately carry a negative balance). A
	// non-empty result means an account was debited past its funds.
	NegativeLedgerAccounts(ctx context.Context, limit int32) ([]NegativeLedgerAccountsRow, error)
	// Committed outbound in the current calendar month, same window/status logic.
	OutboundThisMonth(ctx context.Context, arg OutboundThisMonthParams) (int64, error)
	OutboundThisWeek(ctx context.Context, arg OutboundThisWeekParams) (int64, error)
	OutboundToday(ctx context.Context, arg OutboundTodayParams) (int64, error)
	PauseSchedule(ctx context.Context, arg PauseScheduleParams) (int64, error)
	PaymentRequestByID(ctx context.Context, id uuid.UUID) (PaymentRequest, error)
	PaymentRequestsForUser(ctx context.Context, arg PaymentRequestsForUserParams) ([]PaymentRequest, error)
	PendingTransfersBefore(ctx context.Context, arg PendingTransfersBeforeParams) ([]Transfer, error)
	ProcessingTransfersBefore(ctx context.Context, arg ProcessingTransfersBeforeParams) ([]Transfer, error)
	ProviderWebhookByID(ctx context.Context, id uuid.UUID) (ProviderWebhook, error)
	QuoteByID(ctx context.Context, arg QuoteByIDParams) (TransferQuote, error)
	RecentRecipients(ctx context.Context, arg RecentRecipientsParams) ([]RecentRecipientsRow, error)
	RecordDispatchIntent(ctx context.Context, arg RecordDispatchIntentParams) (ProviderRequest, error)
	// under_review is accepted so a parked payout can be attached to the reference
	// reconciliation eventually finds for it, moving it back into the normal
	// processing lifecycle instead of stranding it.
	RecordProviderDispatch(ctx context.Context, arg RecordProviderDispatchParams) error
	RecordProviderWebhook(ctx context.Context, arg RecordProviderWebhookParams) (ProviderWebhook, error)
	RecordScheduleRun(ctx context.Context, arg RecordScheduleRunParams) (ScheduledPaymentRun, error)
	ReleaseHold(ctx context.Context, id uuid.UUID) (int64, error)
	// The money becomes spendable again by dropping the reservation alone.
	ReleaseWalletReservation(ctx context.Context, arg ReleaseWalletReservationParams) error
	ReserveWallet(ctx context.Context, arg ReserveWalletParams) (int64, error)
	RestoreRoundUpAccrual(ctx context.Context, arg RestoreRoundUpAccrualParams) error
	ResumeSchedule(ctx context.Context, arg ResumeScheduleParams) (int64, error)
	ReviewTransfer(ctx context.Context, arg ReviewTransferParams) (int64, error)
	// Accruals at or over their sweep threshold whose customer has a spend wallet
	// ledger account to debit; the sweep posts ONE ledger transaction per accrual.
	RoundUpAccrualsDueForSweep(ctx context.Context, limit int32) ([]RoundUpAccrualsDueForSweepRow, error)
	RoundUpUnSweptMinor(ctx context.Context, accrualID uuid.UUID) (int64, error)
	ScheduleByID(ctx context.Context, arg ScheduleByIDParams) (ScheduledPayment, error)
	ScheduleRunsBySchedule(ctx context.Context, arg ScheduleRunsByScheduleParams) ([]ScheduledPaymentRun, error)
	// SetFeatureFlag is the single writer of a flag: it upserts so flipping a switch
	// that was never set and re-flipping one that was are the same operation, and
	// stamps updated_at + the human-readable note recording why.
	SetFeatureFlag(ctx context.Context, arg SetFeatureFlagParams) error
	SetPaymentRequestStatus(ctx context.Context, arg SetPaymentRequestStatusParams) (PaymentRequest, error)
	// Closes an intent row with what the rail actually answered.
	SettleDispatchIntent(ctx context.Context, arg SettleDispatchIntentParams) error
	SuggestBanksCatalog(ctx context.Context) ([]SuggestBanksCatalogRow, error)
	TransferByID(ctx context.Context, arg TransferByIDParams) (Transfer, error)
	TransferByKey(ctx context.Context, arg TransferByKeyParams) (Transfer, error)
	TransferByProviderReference(ctx context.Context, arg TransferByProviderReferenceParams) (Transfer, error)
	TransferCountToday(ctx context.Context, arg TransferCountTodayParams) (int64, error)
	TransferEventsByTransfer(ctx context.Context, transferID uuid.UUID) ([]TransferEventsByTransferRow, error)
	TransferInternalByID(ctx context.Context, id uuid.UUID) (Transfer, error)
	TransitionTransfer(ctx context.Context, arg TransitionTransferParams) (int64, error)
	// UnbalancedLedgerTransactions lists any ledger transaction whose entries do not
	// net to zero within a currency. Double-entry means every transaction — posted or
	// reversed — must balance on its own, so this is checked across all of them, not
	// just posted ones. A non-empty result is a hard integrity break. LIMIT bounds the
	// output: existence and a few examples are all the proof needs.
	UnbalancedLedgerTransactions(ctx context.Context, limit int32) ([]UnbalancedLedgerTransactionsRow, error)
	UnderReviewTransfersBefore(ctx context.Context, arg UnderReviewTransfersBeforeParams) ([]Transfer, error)
	UpdateBeneficiaryPresentation(ctx context.Context, arg UpdateBeneficiaryPresentationParams) (Beneficiary, error)
	UpdateSchedulePresentation(ctx context.Context, arg UpdateSchedulePresentationParams) (ScheduledPayment, error)
	UpsertTierLimit(ctx context.Context, arg UpsertTierLimitParams) error
	WalletByIDForUpdate(ctx context.Context, id uuid.UUID) (Wallet, error)
	WalletByUser(ctx context.Context, arg WalletByUserParams) (Wallet, error)
	WalletByUserForUpdate(ctx context.Context, arg WalletByUserForUpdateParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
