// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/identity/identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_GetUser_FullMethodName                = "/nabla.identity.v1.IdentityService/GetUser"
	IdentityService_GetUserByPhone_FullMethodName         = "/nabla.identity.v1.IdentityService/GetUserByPhone"
	IdentityService_GetUserByUsername_FullMethodName      = "/nabla.identity.v1.IdentityService/GetUserByUsername"
	IdentityService_GetUserByAccountNumber_FullMethodName = "/nabla.identity.v1.IdentityService/GetUserByAccountNumber"
	IdentityService_GetKYCProfile_FullMethodName          = "/nabla.identity.v1.IdentityService/GetKYCProfile"
	IdentityService_ValidateKYCTier_FullMethodName        = "/nabla.identity.v1.IdentityService/ValidateKYCTier"
	IdentityService_VerifyPIN_FullMethodName              = "/nabla.identity.v1.IdentityService/VerifyPIN"
	IdentityService_SetPIN_FullMethodName                 = "/nabla.identity.v1.IdentityService/SetPIN"
	IdentityService_RegisterDevice_FullMethodName         = "/nabla.identity.v1.IdentityService/RegisterDevice"
	IdentityService_ValidateDevice_FullMethodName         = "/nabla.identity.v1.IdentityService/ValidateDevice"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService exposes internal identity, KYC, PIN and device operations
// to trusted Nabla services. Calls to this service must be protected by a
// service-authentication interceptor when the gRPC server is enabled.
type IdentityServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByPhone(ctx context.Context, in *GetUserByPhoneRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByAccountNumber(ctx context.Context, in *GetUserByAccountNumberRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetKYCProfile(ctx context.Context, in *GetKYCProfileRequest, opts ...grpc.CallOption) (*GetKYCProfileResponse, error)
	ValidateKYCTier(ctx context.Context, in *ValidateKYCTierRequest, opts ...grpc.CallOption) (*ValidateKYCTierResponse, error)
	VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error)
	SetPIN(ctx context.Context, in *SetPINRequest, opts ...grpc.CallOption) (*SetPINResponse, error)
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	ValidateDevice(ctx context.Context, in *ValidateDeviceRequest, opts ...grpc.CallOption) (*ValidateDeviceResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserByPhone(ctx context.Context, in *GetUserByPhoneRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserByPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserByAccountNumber(ctx context.Context, in *GetUserByAccountNumberRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserByAccountNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetKYCProfile(ctx context.Context, in *GetKYCProfileRequest, opts ...grpc.CallOption) (*GetKYCProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCProfileResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetKYCProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ValidateKYCTier(ctx context.Context, in *ValidateKYCTierRequest, opts ...grpc.CallOption) (*ValidateKYCTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateKYCTierResponse)
	err := c.cc.Invoke(ctx, IdentityService_ValidateKYCTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPINResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SetPIN(ctx context.Context, in *SetPINRequest, opts ...grpc.CallOption) (*SetPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPINResponse)
	err := c.cc.Invoke(ctx, IdentityService_SetPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ValidateDevice(ctx context.Context, in *ValidateDeviceRequest, opts ...grpc.CallOption) (*ValidateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_ValidateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService exposes internal identity, KYC, PIN and device operations
// to trusted Nabla services. Calls to this service must be protected by a
// service-authentication interceptor when the gRPC server is enabled.
type IdentityServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByPhone(context.Context, *GetUserByPhoneRequest) (*GetUserResponse, error)
	GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*GetUserResponse, error)
	GetUserByAccountNumber(context.Context, *GetUserByAccountNumberRequest) (*GetUserResponse, error)
	GetKYCProfile(context.Context, *GetKYCProfileRequest) (*GetKYCProfileResponse, error)
	ValidateKYCTier(context.Context, *ValidateKYCTierRequest) (*ValidateKYCTierResponse, error)
	VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error)
	SetPIN(context.Context, *SetPINRequest) (*SetPINResponse, error)
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	ValidateDevice(context.Context, *ValidateDeviceRequest) (*ValidateDeviceResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserByPhone(context.Context, *GetUserByPhoneRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByPhone not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByUsername not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserByAccountNumber(context.Context, *GetUserByAccountNumberRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByAccountNumber not implemented")
}
func (UnimplementedIdentityServiceServer) GetKYCProfile(context.Context, *GetKYCProfileRequest) (*GetKYCProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKYCProfile not implemented")
}
func (UnimplementedIdentityServiceServer) ValidateKYCTier(context.Context, *ValidateKYCTierRequest) (*ValidateKYCTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateKYCTier not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPIN not implemented")
}
func (UnimplementedIdentityServiceServer) SetPIN(context.Context, *SetPINRequest) (*SetPINResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPIN not implemented")
}
func (UnimplementedIdentityServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedIdentityServiceServer) ValidateDevice(context.Context, *ValidateDeviceRequest) (*ValidateDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateDevice not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserByPhone(ctx, req.(*GetUserByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserByUsername(ctx, req.(*GetUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserByAccountNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByAccountNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserByAccountNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserByAccountNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserByAccountNumber(ctx, req.(*GetUserByAccountNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetKYCProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetKYCProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetKYCProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetKYCProfile(ctx, req.(*GetKYCProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ValidateKYCTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateKYCTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ValidateKYCTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ValidateKYCTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ValidateKYCTier(ctx, req.(*ValidateKYCTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyPIN(ctx, req.(*VerifyPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SetPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SetPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SetPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SetPIN(ctx, req.(*SetPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ValidateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ValidateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ValidateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ValidateDevice(ctx, req.(*ValidateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nabla.identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _IdentityService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByPhone",
			Handler:    _IdentityService_GetUserByPhone_Handler,
		},
		{
			MethodName: "GetUserByUsername",
			Handler:    _IdentityService_GetUserByUsername_Handler,
		},
		{
			MethodName: "GetUserByAccountNumber",
			Handler:    _IdentityService_GetUserByAccountNumber_Handler,
		},
		{
			MethodName: "GetKYCProfile",
			Handler:    _IdentityService_GetKYCProfile_Handler,
		},
		{
			MethodName: "ValidateKYCTier",
			Handler:    _IdentityService_ValidateKYCTier_Handler,
		},
		{
			MethodName: "VerifyPIN",
			Handler:    _IdentityService_VerifyPIN_Handler,
		},
		{
			MethodName: "SetPIN",
			Handler:    _IdentityService_SetPIN_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _IdentityService_RegisterDevice_Handler,
		},
		{
			MethodName: "ValidateDevice",
			Handler:    _IdentityService_ValidateDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identity/identity.proto",
}
