// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authUserByEmail = `-- name: AuthUserByEmail :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE lower(email)=lower($1)
`

func (q *Queries) AuthUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, authUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const authUserByEmailIncludingDeleted = `-- name: AuthUserByEmailIncludingDeleted :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE lower(email)=lower($1)
`

func (q *Queries) AuthUserByEmailIncludingDeleted(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, authUserByEmailIncludingDeleted, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const authUserByID = `-- name: AuthUserByID :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE id=$1
`

func (q *Queries) AuthUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, authUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const authUserByIDIncludingDeleted = `-- name: AuthUserByIDIncludingDeleted :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE id=$1
`

func (q *Queries) AuthUserByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, authUserByIDIncludingDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const authUserByPhoneIncludingDeleted = `-- name: AuthUserByPhoneIncludingDeleted :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE phone_number=$1
`

func (q *Queries) AuthUserByPhoneIncludingDeleted(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, authUserByPhoneIncludingDeleted, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :execrows
UPDATE verification_tokens SET used_at=$2 WHERE id=$1 AND used_at IS NULL AND expires_at>$2
`

type ConsumeVerificationTokenParams struct {
	ID     uuid.UUID  `json:"id"`
	UsedAt *time.Time `json:"used_at"`
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationToken, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO users (id,email,phone_number,password_hash,password_set,role,status,email_verified_at,last_login_at)
VALUES ($1,$2,$3,$4,true,$5,$6,$7,$8) RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type CreateAuthUserParams struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	PhoneNumber     pgtype.Text `json:"phone_number"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	Role            string      `json:"role"`
	Status          string      `json:"status"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	LastLoginAt     *time.Time  `json:"last_login_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.EmailVerifiedAt,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id,user_id,token_hash,family_id,user_agent,ip_address,expires_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, user_id, token_hash, family_id, user_agent, ip_address, last_used_at, revoked_at, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	FamilyID  uuid.UUID   `json:"family_id"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress pgtype.Text `json:"ip_address"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (id,user_id,type,token_hash,requested_ip,user_agent,expires_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, user_id, type, token_hash, requested_ip, user_agent, used_at, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Type        string      `json:"type"`
	TokenHash   string      `json:"token_hash"`
	RequestedIp pgtype.Text `json:"requested_ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
	ExpiresAt   time.Time   `json:"expires_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.TokenHash,
		arg.RequestedIp,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.TokenHash,
		&i.RequestedIp,
		&i.UserAgent,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateVerificationTokens = `-- name: InvalidateVerificationTokens :exec
UPDATE verification_tokens SET used_at=$3 WHERE user_id=$1 AND type=$2 AND used_at IS NULL
`

type InvalidateVerificationTokensParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Type   string     `json:"type"`
	UsedAt *time.Time `json:"used_at"`
}

func (q *Queries) InvalidateVerificationTokens(ctx context.Context, arg InvalidateVerificationTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateVerificationTokens, arg.UserID, arg.Type, arg.UsedAt)
	return err
}

const refreshTokenByHash = `-- name: RefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, user_agent, ip_address, last_used_at, revoked_at, expires_at, created_at FROM refresh_tokens WHERE token_hash=$1
`

func (q *Queries) RefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, refreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users SET status='pending_verification', deleted_at=NULL, updated_at=now() WHERE id=$1 AND deleted_at IS NOT NULL RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at=$2 WHERE id=$1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID        uuid.UUID  `json:"id"`
	RevokedAt *time.Time `json:"revoked_at"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens SET revoked_at=$2 WHERE family_id=$1 AND revoked_at IS NULL
`

type RevokeTokenFamilyParams struct {
	FamilyID  uuid.UUID  `json:"family_id"`
	RevokedAt *time.Time `json:"revoked_at"`
}

func (q *Queries) RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at=$2 WHERE user_id=$1 AND revoked_at IS NULL
`

type RevokeUserRefreshTokensParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	RevokedAt *time.Time `json:"revoked_at"`
}

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, arg RevokeUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, arg.UserID, arg.RevokedAt)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users SET status='deactivated', deleted_at=now(), updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const updateAuthUser = `-- name: UpdateAuthUser :one
UPDATE users SET email=$2,phone_number=$3,password_hash=$4,role=$5,status=$6,email_verified_at=$7,last_login_at=$8,updated_at=now() WHERE id=$1 RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type UpdateAuthUserParams struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	PhoneNumber     pgtype.Text `json:"phone_number"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	Role            string      `json:"role"`
	Status          string      `json:"status"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	LastLoginAt     *time.Time  `json:"last_login_at"`
}

func (q *Queries) UpdateAuthUser(ctx context.Context, arg UpdateAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAuthUser,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.EmailVerifiedAt,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const userByAccountNumber = `-- name: UserByAccountNumber :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE account_number=$1 AND deleted_at IS NULL
`

func (q *Queries) UserByAccountNumber(ctx context.Context, accountNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, userByAccountNumber, accountNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const verificationTokenByHash = `-- name: VerificationTokenByHash :one
SELECT id, user_id, type, token_hash, requested_ip, user_agent, used_at, expires_at, created_at FROM verification_tokens WHERE token_hash=$1
`

func (q *Queries) VerificationTokenByHash(ctx context.Context, tokenHash string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, verificationTokenByHash, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.TokenHash,
		&i.RequestedIp,
		&i.UserAgent,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
