// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package identitydb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyLimitUsageDelta = `-- name: ApplyLimitUsageDelta :execrows
UPDATE limit_usage SET used_minor=used_minor+$2,used_count=used_count+$3,updated_at=now() WHERE id=$1 AND used_minor+$2>=0 AND used_count+$3>=0
`

type ApplyLimitUsageDeltaParams struct {
	ID        uuid.UUID `json:"id"`
	UsedMinor int64     `json:"used_minor"`
	UsedCount int32     `json:"used_count"`
}

func (q *Queries) ApplyLimitUsageDelta(ctx context.Context, arg ApplyLimitUsageDeltaParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyLimitUsageDelta, arg.ID, arg.UsedMinor, arg.UsedCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createKYCAttempt = `-- name: CreateKYCAttempt :one
INSERT INTO kyc_verification_attempts (id,user_id,kind,provider,status,provider_ref,match_score,failure_reason,response_body,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, user_id, kind, provider, status, provider_ref, match_score, failure_reason, response_body, created_at
`

type CreateKYCAttemptParams struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Kind          string      `json:"kind"`
	Provider      string      `json:"provider"`
	Status        string      `json:"status"`
	ProviderRef   pgtype.Text `json:"provider_ref"`
	MatchScore    int32       `json:"match_score"`
	FailureReason pgtype.Text `json:"failure_reason"`
	ResponseBody  []byte      `json:"response_body"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) CreateKYCAttempt(ctx context.Context, arg CreateKYCAttemptParams) (KycVerificationAttempt, error) {
	row := q.db.QueryRow(ctx, createKYCAttempt,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Provider,
		arg.Status,
		arg.ProviderRef,
		arg.MatchScore,
		arg.FailureReason,
		arg.ResponseBody,
		arg.CreatedAt,
	)
	var i KycVerificationAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Provider,
		&i.Status,
		&i.ProviderRef,
		&i.MatchScore,
		&i.FailureReason,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createKYCFacialCapture = `-- name: CreateKYCFacialCapture :one
INSERT INTO kyc_facial_captures (id,user_id,attempt_id,verification_request_id,selfie_image,liveness_frame_images,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, user_id, attempt_id, verification_request_id, selfie_image, liveness_frame_images, created_at
`

type CreateKYCFacialCaptureParams struct {
	ID                    uuid.UUID       `json:"id"`
	UserID                uuid.UUID       `json:"user_id"`
	AttemptID             uuid.UUID       `json:"attempt_id"`
	VerificationRequestID pgtype.Text     `json:"verification_request_id"`
	SelfieImage           []byte          `json:"selfie_image"`
	LivenessFrameImages   json.RawMessage `json:"liveness_frame_images"`
	CreatedAt             time.Time       `json:"created_at"`
}

func (q *Queries) CreateKYCFacialCapture(ctx context.Context, arg CreateKYCFacialCaptureParams) (KycFacialCapture, error) {
	row := q.db.QueryRow(ctx, createKYCFacialCapture,
		arg.ID,
		arg.UserID,
		arg.AttemptID,
		arg.VerificationRequestID,
		arg.SelfieImage,
		arg.LivenessFrameImages,
		arg.CreatedAt,
	)
	var i KycFacialCapture
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AttemptID,
		&i.VerificationRequestID,
		&i.SelfieImage,
		&i.LivenessFrameImages,
		&i.CreatedAt,
	)
	return i, err
}

const createKYCProfile = `-- name: CreateKYCProfile :one
INSERT INTO kyc_profiles (id,user_id,tier,first_name,middle_name,last_name,date_of_birth,gender,phone_number,phone_status,phone_verified_at,bvn_encrypted,bvn_last4,bvn_hash,bvn_status,bvn_verified_at,bvn_phone_verified_at,bvn_provider_ref,bvn_selfie_status,bvn_liveness_score,bvn_face_match_score,bvn_selfie_verified_at,nin_encrypted,nin_last4,nin_hash,nin_status,nin_verified_at,address_line1,address_line2,city,state,postal_code,country,address_status,sanctioned,pep,reject_reason,provider_payload,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40) RETURNING id, user_id, tier, first_name, middle_name, last_name, date_of_birth, gender, phone_number, phone_status, phone_verified_at, bvn_encrypted, bvn_last4, bvn_hash, bvn_status, bvn_verified_at, bvn_phone_verified_at, bvn_provider_ref, bvn_selfie_status, bvn_liveness_score, bvn_face_match_score, bvn_selfie_verified_at, nin_encrypted, nin_last4, nin_hash, nin_status, nin_verified_at, address_line1, address_line2, city, state, postal_code, country, address_status, sanctioned, pep, reject_reason, provider_payload, created_at, updated_at
`

type CreateKYCProfileParams struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	Tier                int16       `json:"tier"`
	FirstName           pgtype.Text `json:"first_name"`
	MiddleName          pgtype.Text `json:"middle_name"`
	LastName            pgtype.Text `json:"last_name"`
	DateOfBirth         *time.Time  `json:"date_of_birth"`
	Gender              pgtype.Text `json:"gender"`
	PhoneNumber         pgtype.Text `json:"phone_number"`
	PhoneStatus         string      `json:"phone_status"`
	PhoneVerifiedAt     *time.Time  `json:"phone_verified_at"`
	BvnEncrypted        pgtype.Text `json:"bvn_encrypted"`
	BvnLast4            pgtype.Text `json:"bvn_last4"`
	BvnHash             pgtype.Text `json:"bvn_hash"`
	BvnStatus           string      `json:"bvn_status"`
	BvnVerifiedAt       *time.Time  `json:"bvn_verified_at"`
	BvnPhoneVerifiedAt  *time.Time  `json:"bvn_phone_verified_at"`
	BvnProviderRef      pgtype.Text `json:"bvn_provider_ref"`
	BvnSelfieStatus     string      `json:"bvn_selfie_status"`
	BvnLivenessScore    float64     `json:"bvn_liveness_score"`
	BvnFaceMatchScore   float64     `json:"bvn_face_match_score"`
	BvnSelfieVerifiedAt *time.Time  `json:"bvn_selfie_verified_at"`
	NinEncrypted        pgtype.Text `json:"nin_encrypted"`
	NinLast4            pgtype.Text `json:"nin_last4"`
	NinHash             pgtype.Text `json:"nin_hash"`
	NinStatus           string      `json:"nin_status"`
	NinVerifiedAt       *time.Time  `json:"nin_verified_at"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	State               pgtype.Text `json:"state"`
	PostalCode          pgtype.Text `json:"postal_code"`
	Country             string      `json:"country"`
	AddressStatus       string      `json:"address_status"`
	Sanctioned          bool        `json:"sanctioned"`
	Pep                 bool        `json:"pep"`
	RejectReason        pgtype.Text `json:"reject_reason"`
	ProviderPayload     []byte      `json:"provider_payload"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) CreateKYCProfile(ctx context.Context, arg CreateKYCProfileParams) (KycProfile, error) {
	row := q.db.QueryRow(ctx, createKYCProfile,
		arg.ID,
		arg.UserID,
		arg.Tier,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.PhoneNumber,
		arg.PhoneStatus,
		arg.PhoneVerifiedAt,
		arg.BvnEncrypted,
		arg.BvnLast4,
		arg.BvnHash,
		arg.BvnStatus,
		arg.BvnVerifiedAt,
		arg.BvnPhoneVerifiedAt,
		arg.BvnProviderRef,
		arg.BvnSelfieStatus,
		arg.BvnLivenessScore,
		arg.BvnFaceMatchScore,
		arg.BvnSelfieVerifiedAt,
		arg.NinEncrypted,
		arg.NinLast4,
		arg.NinHash,
		arg.NinStatus,
		arg.NinVerifiedAt,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.AddressStatus,
		arg.Sanctioned,
		arg.Pep,
		arg.RejectReason,
		arg.ProviderPayload,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PhoneNumber,
		&i.PhoneStatus,
		&i.PhoneVerifiedAt,
		&i.BvnEncrypted,
		&i.BvnLast4,
		&i.BvnHash,
		&i.BvnStatus,
		&i.BvnVerifiedAt,
		&i.BvnPhoneVerifiedAt,
		&i.BvnProviderRef,
		&i.BvnSelfieStatus,
		&i.BvnLivenessScore,
		&i.BvnFaceMatchScore,
		&i.BvnSelfieVerifiedAt,
		&i.NinEncrypted,
		&i.NinLast4,
		&i.NinHash,
		&i.NinStatus,
		&i.NinVerifiedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.AddressStatus,
		&i.Sanctioned,
		&i.Pep,
		&i.RejectReason,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureLimitUsage = `-- name: EnsureLimitUsage :exec
INSERT INTO limit_usage (id,user_id,currency,window_type,window_key) VALUES (gen_random_uuid(),$1,$2,$3,$4) ON CONFLICT (user_id,currency,window_type,window_key) DO NOTHING
`

type EnsureLimitUsageParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Currency   string    `json:"currency"`
	WindowType string    `json:"window_type"`
	WindowKey  string    `json:"window_key"`
}

func (q *Queries) EnsureLimitUsage(ctx context.Context, arg EnsureLimitUsageParams) error {
	_, err := q.db.Exec(ctx, ensureLimitUsage,
		arg.UserID,
		arg.Currency,
		arg.WindowType,
		arg.WindowKey,
	)
	return err
}

const kYCAttemptsByUserID = `-- name: KYCAttemptsByUserID :many
SELECT id, user_id, kind, provider, status, provider_ref, match_score, failure_reason, response_body, created_at FROM kyc_verification_attempts WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2
`

type KYCAttemptsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) KYCAttemptsByUserID(ctx context.Context, arg KYCAttemptsByUserIDParams) ([]KycVerificationAttempt, error) {
	rows, err := q.db.Query(ctx, kYCAttemptsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycVerificationAttempt{}
	for rows.Next() {
		var i KycVerificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Provider,
			&i.Status,
			&i.ProviderRef,
			&i.MatchScore,
			&i.FailureReason,
			&i.ResponseBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kYCProfileByBVNHash = `-- name: KYCProfileByBVNHash :one
SELECT id, user_id, tier, first_name, middle_name, last_name, date_of_birth, gender, phone_number, phone_status, phone_verified_at, bvn_encrypted, bvn_last4, bvn_hash, bvn_status, bvn_verified_at, bvn_phone_verified_at, bvn_provider_ref, bvn_selfie_status, bvn_liveness_score, bvn_face_match_score, bvn_selfie_verified_at, nin_encrypted, nin_last4, nin_hash, nin_status, nin_verified_at, address_line1, address_line2, city, state, postal_code, country, address_status, sanctioned, pep, reject_reason, provider_payload, created_at, updated_at FROM kyc_profiles WHERE bvn_hash=$1
`

func (q *Queries) KYCProfileByBVNHash(ctx context.Context, bvnHash pgtype.Text) (KycProfile, error) {
	row := q.db.QueryRow(ctx, kYCProfileByBVNHash, bvnHash)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PhoneNumber,
		&i.PhoneStatus,
		&i.PhoneVerifiedAt,
		&i.BvnEncrypted,
		&i.BvnLast4,
		&i.BvnHash,
		&i.BvnStatus,
		&i.BvnVerifiedAt,
		&i.BvnPhoneVerifiedAt,
		&i.BvnProviderRef,
		&i.BvnSelfieStatus,
		&i.BvnLivenessScore,
		&i.BvnFaceMatchScore,
		&i.BvnSelfieVerifiedAt,
		&i.NinEncrypted,
		&i.NinLast4,
		&i.NinHash,
		&i.NinStatus,
		&i.NinVerifiedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.AddressStatus,
		&i.Sanctioned,
		&i.Pep,
		&i.RejectReason,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kYCProfileByNINHash = `-- name: KYCProfileByNINHash :one
SELECT id, user_id, tier, first_name, middle_name, last_name, date_of_birth, gender, phone_number, phone_status, phone_verified_at, bvn_encrypted, bvn_last4, bvn_hash, bvn_status, bvn_verified_at, bvn_phone_verified_at, bvn_provider_ref, bvn_selfie_status, bvn_liveness_score, bvn_face_match_score, bvn_selfie_verified_at, nin_encrypted, nin_last4, nin_hash, nin_status, nin_verified_at, address_line1, address_line2, city, state, postal_code, country, address_status, sanctioned, pep, reject_reason, provider_payload, created_at, updated_at FROM kyc_profiles WHERE nin_hash=$1
`

func (q *Queries) KYCProfileByNINHash(ctx context.Context, ninHash pgtype.Text) (KycProfile, error) {
	row := q.db.QueryRow(ctx, kYCProfileByNINHash, ninHash)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PhoneNumber,
		&i.PhoneStatus,
		&i.PhoneVerifiedAt,
		&i.BvnEncrypted,
		&i.BvnLast4,
		&i.BvnHash,
		&i.BvnStatus,
		&i.BvnVerifiedAt,
		&i.BvnPhoneVerifiedAt,
		&i.BvnProviderRef,
		&i.BvnSelfieStatus,
		&i.BvnLivenessScore,
		&i.BvnFaceMatchScore,
		&i.BvnSelfieVerifiedAt,
		&i.NinEncrypted,
		&i.NinLast4,
		&i.NinHash,
		&i.NinStatus,
		&i.NinVerifiedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.AddressStatus,
		&i.Sanctioned,
		&i.Pep,
		&i.RejectReason,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kYCProfileByUserID = `-- name: KYCProfileByUserID :one
SELECT id, user_id, tier, first_name, middle_name, last_name, date_of_birth, gender, phone_number, phone_status, phone_verified_at, bvn_encrypted, bvn_last4, bvn_hash, bvn_status, bvn_verified_at, bvn_phone_verified_at, bvn_provider_ref, bvn_selfie_status, bvn_liveness_score, bvn_face_match_score, bvn_selfie_verified_at, nin_encrypted, nin_last4, nin_hash, nin_status, nin_verified_at, address_line1, address_line2, city, state, postal_code, country, address_status, sanctioned, pep, reject_reason, provider_payload, created_at, updated_at FROM kyc_profiles WHERE user_id=$1
`

func (q *Queries) KYCProfileByUserID(ctx context.Context, userID uuid.UUID) (KycProfile, error) {
	row := q.db.QueryRow(ctx, kYCProfileByUserID, userID)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PhoneNumber,
		&i.PhoneStatus,
		&i.PhoneVerifiedAt,
		&i.BvnEncrypted,
		&i.BvnLast4,
		&i.BvnHash,
		&i.BvnStatus,
		&i.BvnVerifiedAt,
		&i.BvnPhoneVerifiedAt,
		&i.BvnProviderRef,
		&i.BvnSelfieStatus,
		&i.BvnLivenessScore,
		&i.BvnFaceMatchScore,
		&i.BvnSelfieVerifiedAt,
		&i.NinEncrypted,
		&i.NinLast4,
		&i.NinHash,
		&i.NinStatus,
		&i.NinVerifiedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.AddressStatus,
		&i.Sanctioned,
		&i.Pep,
		&i.RejectReason,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const limitForTier = `-- name: LimitForTier :one
SELECT id, tier, currency, single_transaction_max_minor, daily_max_minor, monthly_max_minor, max_balance_minor, daily_count_max, created_at, updated_at FROM transaction_limits WHERE tier=$1 AND currency=$2
`

type LimitForTierParams struct {
	Tier     int16  `json:"tier"`
	Currency string `json:"currency"`
}

func (q *Queries) LimitForTier(ctx context.Context, arg LimitForTierParams) (TransactionLimit, error) {
	row := q.db.QueryRow(ctx, limitForTier, arg.Tier, arg.Currency)
	var i TransactionLimit
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Currency,
		&i.SingleTransactionMaxMinor,
		&i.DailyMaxMinor,
		&i.MonthlyMaxMinor,
		&i.MaxBalanceMinor,
		&i.DailyCountMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionLimits = `-- name: ListTransactionLimits :many
SELECT id, tier, currency, single_transaction_max_minor, daily_max_minor, monthly_max_minor, max_balance_minor, daily_count_max, created_at, updated_at FROM transaction_limits ORDER BY tier,currency
`

func (q *Queries) ListTransactionLimits(ctx context.Context) ([]TransactionLimit, error) {
	rows, err := q.db.Query(ctx, listTransactionLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionLimit{}
	for rows.Next() {
		var i TransactionLimit
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Currency,
			&i.SingleTransactionMaxMinor,
			&i.DailyMaxMinor,
			&i.MonthlyMaxMinor,
			&i.MaxBalanceMinor,
			&i.DailyCountMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLimitUsage = `-- name: LockLimitUsage :one
SELECT id, user_id, currency, window_type, window_key, used_minor, used_count, created_at, updated_at FROM limit_usage WHERE user_id=$1 AND currency=$2 AND window_type=$3 AND window_key=$4 FOR UPDATE
`

type LockLimitUsageParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Currency   string    `json:"currency"`
	WindowType string    `json:"window_type"`
	WindowKey  string    `json:"window_key"`
}

func (q *Queries) LockLimitUsage(ctx context.Context, arg LockLimitUsageParams) (LimitUsage, error) {
	row := q.db.QueryRow(ctx, lockLimitUsage,
		arg.UserID,
		arg.Currency,
		arg.WindowType,
		arg.WindowKey,
	)
	var i LimitUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.WindowType,
		&i.WindowKey,
		&i.UsedMinor,
		&i.UsedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recentKYCAttemptCount = `-- name: RecentKYCAttemptCount :one
SELECT count(*) FROM kyc_verification_attempts WHERE user_id=$1 AND kind=$2 AND created_at >= $3
`

type RecentKYCAttemptCountParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) RecentKYCAttemptCount(ctx context.Context, arg RecentKYCAttemptCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, recentKYCAttemptCount, arg.UserID, arg.Kind, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateKYCProfile = `-- name: UpdateKYCProfile :one
UPDATE kyc_profiles SET tier=$2,first_name=$3,middle_name=$4,last_name=$5,date_of_birth=$6,gender=$7,phone_number=$8,phone_status=$9,phone_verified_at=$10,bvn_encrypted=$11,bvn_last4=$12,bvn_hash=$13,bvn_status=$14,bvn_verified_at=$15,bvn_phone_verified_at=$16,bvn_provider_ref=$17,bvn_selfie_status=$18,bvn_liveness_score=$19,bvn_face_match_score=$20,bvn_selfie_verified_at=$21,nin_encrypted=$22,nin_last4=$23,nin_hash=$24,nin_status=$25,nin_verified_at=$26,address_line1=$27,address_line2=$28,city=$29,state=$30,postal_code=$31,country=$32,address_status=$33,sanctioned=$34,pep=$35,reject_reason=$36,provider_payload=$37,updated_at=now() WHERE id=$1 RETURNING id, user_id, tier, first_name, middle_name, last_name, date_of_birth, gender, phone_number, phone_status, phone_verified_at, bvn_encrypted, bvn_last4, bvn_hash, bvn_status, bvn_verified_at, bvn_phone_verified_at, bvn_provider_ref, bvn_selfie_status, bvn_liveness_score, bvn_face_match_score, bvn_selfie_verified_at, nin_encrypted, nin_last4, nin_hash, nin_status, nin_verified_at, address_line1, address_line2, city, state, postal_code, country, address_status, sanctioned, pep, reject_reason, provider_payload, created_at, updated_at
`

type UpdateKYCProfileParams struct {
	ID                  uuid.UUID   `json:"id"`
	Tier                int16       `json:"tier"`
	FirstName           pgtype.Text `json:"first_name"`
	MiddleName          pgtype.Text `json:"middle_name"`
	LastName            pgtype.Text `json:"last_name"`
	DateOfBirth         *time.Time  `json:"date_of_birth"`
	Gender              pgtype.Text `json:"gender"`
	PhoneNumber         pgtype.Text `json:"phone_number"`
	PhoneStatus         string      `json:"phone_status"`
	PhoneVerifiedAt     *time.Time  `json:"phone_verified_at"`
	BvnEncrypted        pgtype.Text `json:"bvn_encrypted"`
	BvnLast4            pgtype.Text `json:"bvn_last4"`
	BvnHash             pgtype.Text `json:"bvn_hash"`
	BvnStatus           string      `json:"bvn_status"`
	BvnVerifiedAt       *time.Time  `json:"bvn_verified_at"`
	BvnPhoneVerifiedAt  *time.Time  `json:"bvn_phone_verified_at"`
	BvnProviderRef      pgtype.Text `json:"bvn_provider_ref"`
	BvnSelfieStatus     string      `json:"bvn_selfie_status"`
	BvnLivenessScore    float64     `json:"bvn_liveness_score"`
	BvnFaceMatchScore   float64     `json:"bvn_face_match_score"`
	BvnSelfieVerifiedAt *time.Time  `json:"bvn_selfie_verified_at"`
	NinEncrypted        pgtype.Text `json:"nin_encrypted"`
	NinLast4            pgtype.Text `json:"nin_last4"`
	NinHash             pgtype.Text `json:"nin_hash"`
	NinStatus           string      `json:"nin_status"`
	NinVerifiedAt       *time.Time  `json:"nin_verified_at"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	State               pgtype.Text `json:"state"`
	PostalCode          pgtype.Text `json:"postal_code"`
	Country             string      `json:"country"`
	AddressStatus       string      `json:"address_status"`
	Sanctioned          bool        `json:"sanctioned"`
	Pep                 bool        `json:"pep"`
	RejectReason        pgtype.Text `json:"reject_reason"`
	ProviderPayload     []byte      `json:"provider_payload"`
}

func (q *Queries) UpdateKYCProfile(ctx context.Context, arg UpdateKYCProfileParams) (KycProfile, error) {
	row := q.db.QueryRow(ctx, updateKYCProfile,
		arg.ID,
		arg.Tier,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.PhoneNumber,
		arg.PhoneStatus,
		arg.PhoneVerifiedAt,
		arg.BvnEncrypted,
		arg.BvnLast4,
		arg.BvnHash,
		arg.BvnStatus,
		arg.BvnVerifiedAt,
		arg.BvnPhoneVerifiedAt,
		arg.BvnProviderRef,
		arg.BvnSelfieStatus,
		arg.BvnLivenessScore,
		arg.BvnFaceMatchScore,
		arg.BvnSelfieVerifiedAt,
		arg.NinEncrypted,
		arg.NinLast4,
		arg.NinHash,
		arg.NinStatus,
		arg.NinVerifiedAt,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.AddressStatus,
		arg.Sanctioned,
		arg.Pep,
		arg.RejectReason,
		arg.ProviderPayload,
	)
	var i KycProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PhoneNumber,
		&i.PhoneStatus,
		&i.PhoneVerifiedAt,
		&i.BvnEncrypted,
		&i.BvnLast4,
		&i.BvnHash,
		&i.BvnStatus,
		&i.BvnVerifiedAt,
		&i.BvnPhoneVerifiedAt,
		&i.BvnProviderRef,
		&i.BvnSelfieStatus,
		&i.BvnLivenessScore,
		&i.BvnFaceMatchScore,
		&i.BvnSelfieVerifiedAt,
		&i.NinEncrypted,
		&i.NinLast4,
		&i.NinHash,
		&i.NinStatus,
		&i.NinVerifiedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.AddressStatus,
		&i.Sanctioned,
		&i.Pep,
		&i.RejectReason,
		&i.ProviderPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTransactionLimit = `-- name: UpsertTransactionLimit :one
INSERT INTO transaction_limits (id,tier,currency,single_transaction_max_minor,daily_max_minor,monthly_max_minor,max_balance_minor,daily_count_max,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (tier,currency) DO UPDATE SET single_transaction_max_minor=excluded.single_transaction_max_minor,daily_max_minor=excluded.daily_max_minor,monthly_max_minor=excluded.monthly_max_minor,max_balance_minor=excluded.max_balance_minor,daily_count_max=excluded.daily_count_max,updated_at=now() RETURNING id, tier, currency, single_transaction_max_minor, daily_max_minor, monthly_max_minor, max_balance_minor, daily_count_max, created_at, updated_at
`

type UpsertTransactionLimitParams struct {
	ID                        uuid.UUID `json:"id"`
	Tier                      int16     `json:"tier"`
	Currency                  string    `json:"currency"`
	SingleTransactionMaxMinor int64     `json:"single_transaction_max_minor"`
	DailyMaxMinor             int64     `json:"daily_max_minor"`
	MonthlyMaxMinor           int64     `json:"monthly_max_minor"`
	MaxBalanceMinor           int64     `json:"max_balance_minor"`
	DailyCountMax             int32     `json:"daily_count_max"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

func (q *Queries) UpsertTransactionLimit(ctx context.Context, arg UpsertTransactionLimitParams) (TransactionLimit, error) {
	row := q.db.QueryRow(ctx, upsertTransactionLimit,
		arg.ID,
		arg.Tier,
		arg.Currency,
		arg.SingleTransactionMaxMinor,
		arg.DailyMaxMinor,
		arg.MonthlyMaxMinor,
		arg.MaxBalanceMinor,
		arg.DailyCountMax,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TransactionLimit
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Currency,
		&i.SingleTransactionMaxMinor,
		&i.DailyMaxMinor,
		&i.MonthlyMaxMinor,
		&i.MaxBalanceMinor,
		&i.DailyCountMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usageForWindow = `-- name: UsageForWindow :one
SELECT id, user_id, currency, window_type, window_key, used_minor, used_count, created_at, updated_at FROM limit_usage WHERE user_id=$1 AND currency=$2 AND window_type=$3 AND window_key=$4
`

type UsageForWindowParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Currency   string    `json:"currency"`
	WindowType string    `json:"window_type"`
	WindowKey  string    `json:"window_key"`
}

func (q *Queries) UsageForWindow(ctx context.Context, arg UsageForWindowParams) (LimitUsage, error) {
	row := q.db.QueryRow(ctx, usageForWindow,
		arg.UserID,
		arg.Currency,
		arg.WindowType,
		arg.WindowKey,
	)
	var i LimitUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.WindowType,
		&i.WindowKey,
		&i.UsedMinor,
		&i.UsedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
