// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountClosureRequest struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	Reason           string      `json:"reason"`
	ReasonNote       pgtype.Text `json:"reason_note"`
	Status           string      `json:"status"`
	FacialVerifiedAt *time.Time  `json:"facial_verified_at"`
	CodeHash         pgtype.Text `json:"code_hash"`
	CodeExpiresAt    *time.Time  `json:"code_expires_at"`
	CodeAttempts     int32       `json:"code_attempts"`
	ConfirmedAt      *time.Time  `json:"confirmed_at"`
	RestoredAt       *time.Time  `json:"restored_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type AuditLog struct {
	ID          uuid.UUID   `json:"id"`
	ActorType   string      `json:"actor_type"`
	ActorID     *uuid.UUID  `json:"actor_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    *uuid.UUID  `json:"entity_id"`
	BeforeState []byte      `json:"before_state"`
	AfterState  []byte      `json:"after_state"`
	RequestID   pgtype.Text `json:"request_id"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	CreatedAt   time.Time   `json:"created_at"`
}

type AuthIdentity struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	ProviderEmail  pgtype.Text `json:"provider_email"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type CreatorProfile struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type CreatorSocialLink struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
	Platform  string    `json:"platform"`
	Url       string    `json:"url"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type KycFacialCapture struct {
	ID                    uuid.UUID       `json:"id"`
	UserID                uuid.UUID       `json:"user_id"`
	AttemptID             uuid.UUID       `json:"attempt_id"`
	VerificationRequestID pgtype.Text     `json:"verification_request_id"`
	SelfieImage           []byte          `json:"selfie_image"`
	LivenessFrameImages   json.RawMessage `json:"liveness_frame_images"`
	CreatedAt             time.Time       `json:"created_at"`
}

type KycProfile struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	Tier                int16       `json:"tier"`
	FirstName           pgtype.Text `json:"first_name"`
	MiddleName          pgtype.Text `json:"middle_name"`
	LastName            pgtype.Text `json:"last_name"`
	DateOfBirth         *time.Time  `json:"date_of_birth"`
	Gender              pgtype.Text `json:"gender"`
	PhoneNumber         pgtype.Text `json:"phone_number"`
	PhoneStatus         string      `json:"phone_status"`
	PhoneVerifiedAt     *time.Time  `json:"phone_verified_at"`
	BvnEncrypted        pgtype.Text `json:"bvn_encrypted"`
	BvnLast4            pgtype.Text `json:"bvn_last4"`
	BvnHash             pgtype.Text `json:"bvn_hash"`
	BvnStatus           string      `json:"bvn_status"`
	BvnVerifiedAt       *time.Time  `json:"bvn_verified_at"`
	BvnPhoneVerifiedAt  *time.Time  `json:"bvn_phone_verified_at"`
	BvnProviderRef      pgtype.Text `json:"bvn_provider_ref"`
	BvnSelfieStatus     string      `json:"bvn_selfie_status"`
	BvnLivenessScore    float64     `json:"bvn_liveness_score"`
	BvnFaceMatchScore   float64     `json:"bvn_face_match_score"`
	BvnSelfieVerifiedAt *time.Time  `json:"bvn_selfie_verified_at"`
	NinEncrypted        pgtype.Text `json:"nin_encrypted"`
	NinLast4            pgtype.Text `json:"nin_last4"`
	NinHash             pgtype.Text `json:"nin_hash"`
	NinStatus           string      `json:"nin_status"`
	NinVerifiedAt       *time.Time  `json:"nin_verified_at"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	State               pgtype.Text `json:"state"`
	PostalCode          pgtype.Text `json:"postal_code"`
	Country             string      `json:"country"`
	AddressStatus       string      `json:"address_status"`
	Sanctioned          bool        `json:"sanctioned"`
	Pep                 bool        `json:"pep"`
	RejectReason        pgtype.Text `json:"reject_reason"`
	ProviderPayload     []byte      `json:"provider_payload"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type KycVerificationAttempt struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Kind          string      `json:"kind"`
	Provider      string      `json:"provider"`
	Status        string      `json:"status"`
	ProviderRef   pgtype.Text `json:"provider_ref"`
	MatchScore    int32       `json:"match_score"`
	FailureReason pgtype.Text `json:"failure_reason"`
	ResponseBody  []byte      `json:"response_body"`
	CreatedAt     time.Time   `json:"created_at"`
}

type LimitUsage struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Currency   string    `json:"currency"`
	WindowType string    `json:"window_type"`
	WindowKey  string    `json:"window_key"`
	UsedMinor  int64     `json:"used_minor"`
	UsedCount  int32     `json:"used_count"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type OtpCode struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Purpose        string     `json:"purpose"`
	Channel        string     `json:"channel"`
	Destination    string     `json:"destination"`
	CodeHash       string     `json:"code_hash"`
	ChallengeToken string     `json:"challenge_token"`
	FailedAttempts int32      `json:"failed_attempts"`
	ConsumedAt     *time.Time `json:"consumed_at"`
	ExpiresAt      time.Time  `json:"expires_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	Exchange      string          `json:"exchange"`
	RoutingKey    string          `json:"routing_key"`
	EventType     string          `json:"event_type"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	Payload       json.RawMessage `json:"payload"`
	Status        string          `json:"status"`
	Attempts      int32           `json:"attempts"`
	LastError     pgtype.Text     `json:"last_error"`
	AvailableAt   time.Time       `json:"available_at"`
	PublishedAt   *time.Time      `json:"published_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	FamilyID   uuid.UUID   `json:"family_id"`
	UserAgent  pgtype.Text `json:"user_agent"`
	IpAddress  pgtype.Text `json:"ip_address"`
	LastUsedAt *time.Time  `json:"last_used_at"`
	RevokedAt  *time.Time  `json:"revoked_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	CreatedAt  time.Time   `json:"created_at"`
}

type RiskAssessment struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Operation      string      `json:"operation"`
	Decision       string      `json:"decision"`
	Score          int32       `json:"score"`
	TriggeredRules pgtype.Text `json:"triggered_rules"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       pgtype.Text `json:"currency"`
	DeviceID       *uuid.UUID  `json:"device_id"`
	IpAddress      pgtype.Text `json:"ip_address"`
	Reference      pgtype.Text `json:"reference"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Tier3Application struct {
	ID                     uuid.UUID     `json:"id"`
	UserID                 uuid.UUID     `json:"user_id"`
	Status                 string        `json:"status"`
	NinStatus              string        `json:"nin_status"`
	AddressStatus          string        `json:"address_status"`
	LocationStatus         string        `json:"location_status"`
	UtilityDocumentStatus  string        `json:"utility_document_status"`
	AddressText            pgtype.Text   `json:"address_text"`
	AddressLine1           pgtype.Text   `json:"address_line1"`
	AddressLine2           pgtype.Text   `json:"address_line2"`
	City                   pgtype.Text   `json:"city"`
	State                  pgtype.Text   `json:"state"`
	CountryCode            string        `json:"country_code"`
	PostalCode             pgtype.Text   `json:"postal_code"`
	Latitude               pgtype.Float8 `json:"latitude"`
	Longitude              pgtype.Float8 `json:"longitude"`
	AccuracyMeters         pgtype.Float8 `json:"accuracy_meters"`
	LocationProvider       pgtype.Text   `json:"location_provider"`
	LocationMocked         bool          `json:"location_mocked"`
	LocationCapturedAt     *time.Time    `json:"location_captured_at"`
	LocationConsentAt      *time.Time    `json:"location_consent_at"`
	ReverseGeocodedAddress pgtype.Text   `json:"reverse_geocoded_address"`
	DistanceMeters         pgtype.Float8 `json:"distance_meters"`
	SubmittedAt            *time.Time    `json:"submitted_at"`
	ApprovedAt             *time.Time    `json:"approved_at"`
	ReviewedAt             *time.Time    `json:"reviewed_at"`
	ReviewedBy             *uuid.UUID    `json:"reviewed_by"`
	RejectionReason        pgtype.Text   `json:"rejection_reason"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at"`
}

type Tier3Document struct {
	ID               uuid.UUID   `json:"id"`
	ApplicationID    uuid.UUID   `json:"application_id"`
	UserID           uuid.UUID   `json:"user_id"`
	DocumentType     string      `json:"document_type"`
	OriginalFilename string      `json:"original_filename"`
	IssueDate        time.Time   `json:"issue_date"`
	ObjectKey        string      `json:"object_key"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	Sha256           string      `json:"sha256"`
	Etag             pgtype.Text `json:"etag"`
	UploadExpiresAt  *time.Time  `json:"upload_expires_at"`
	UploadedAt       *time.Time  `json:"uploaded_at"`
	ExtractedName    pgtype.Text `json:"extracted_name"`
	ExtractedAddress pgtype.Text `json:"extracted_address"`
	Status           string      `json:"status"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	CreatedAt        time.Time   `json:"created_at"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
}

type TransactionLimit struct {
	ID                        uuid.UUID `json:"id"`
	Tier                      int16     `json:"tier"`
	Currency                  string    `json:"currency"`
	SingleTransactionMaxMinor int64     `json:"single_transaction_max_minor"`
	DailyMaxMinor             int64     `json:"daily_max_minor"`
	MonthlyMaxMinor           int64     `json:"monthly_max_minor"`
	MaxBalanceMinor           int64     `json:"max_balance_minor"`
	DailyCountMax             int32     `json:"daily_count_max"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

type TransactionPin struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	PinHash        string     `json:"pin_hash"`
	FailedAttempts int32      `json:"failed_attempts"`
	LockedUntil    *time.Time `json:"locked_until"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	LastChangedAt  time.Time  `json:"last_changed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Email           pgtype.Text `json:"email"`
	PhoneNumber     pgtype.Text `json:"phone_number"`
	NablrUsername   pgtype.Text `json:"nablr_username"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	PasswordSet     bool        `json:"password_set"`
	Role            string      `json:"role"`
	Status          string      `json:"status"`
	PhoneVerified   bool        `json:"phone_verified"`
	PhoneVerifiedAt *time.Time  `json:"phone_verified_at"`
	OtpCode         pgtype.Text `json:"otp_code"`
	OtpExpiresAt    *time.Time  `json:"otp_expires_at"`
	NinStatus       string      `json:"nin_status"`
	NinVerified     bool        `json:"nin_verified"`
	FacialStatus    string      `json:"facial_status"`
	FacialVerified  bool        `json:"facial_verified"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	LastLoginAt     *time.Time  `json:"last_login_at"`
	DeletedAt       *time.Time  `json:"deleted_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	AccountNumber   pgtype.Text `json:"account_number"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
}

type UserDevice struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Fingerprint string        `json:"fingerprint"`
	Name        pgtype.Text   `json:"name"`
	Platform    pgtype.Text   `json:"platform"`
	PushToken   pgtype.Text   `json:"push_token"`
	AppVersion  pgtype.Text   `json:"app_version"`
	OsVersion   pgtype.Text   `json:"os_version"`
	DeviceModel pgtype.Text   `json:"device_model"`
	Trusted     bool          `json:"trusted"`
	Blocked     bool          `json:"blocked"`
	LastIp      pgtype.Text   `json:"last_ip"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	LastSeenAt  *time.Time    `json:"last_seen_at"`
	TrustedAt   *time.Time    `json:"trusted_at"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type VerificationToken struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Type        string      `json:"type"`
	TokenHash   string      `json:"token_hash"`
	RequestedIp pgtype.Text `json:"requested_ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
	UsedAt      *time.Time  `json:"used_at"`
	ExpiresAt   time.Time   `json:"expires_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

type WaitlistEntry struct {
	ID                   uuid.UUID   `json:"id"`
	NablrUsername        string      `json:"nablr_username"`
	Email                pgtype.Text `json:"email"`
	ReservationTokenHash string      `json:"reservation_token_hash"`
	Status               string      `json:"status"`
	HeldAt               time.Time   `json:"held_at"`
	HoldExpiresAt        time.Time   `json:"hold_expires_at"`
	ConfirmedAt          *time.Time  `json:"confirmed_at"`
	ExpiresAt            *time.Time  `json:"expires_at"`
	ClaimedUserID        *uuid.UUID  `json:"claimed_user_id"`
	ClaimedAt            *time.Time  `json:"claimed_at"`
	RequestedIp          pgtype.Text `json:"requested_ip"`
	UserAgent            pgtype.Text `json:"user_agent"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}
