// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package identitydb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, exchange, routing_key, event_type, aggregate_type, aggregate_id, payload, status, attempts, last_error, available_at, published_at, created_at, updated_at FROM outbox_events WHERE status IN ('pending','failed') AND available_at<=$1 ORDER BY available_at,id LIMIT $2 FOR UPDATE SKIP LOCKED
`

type ClaimOutboxBatchParams struct {
	AvailableAt time.Time `json:"available_at"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.AvailableAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Exchange,
			&i.RoutingKey,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.AvailableAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs WHERE ($1::uuid IS NULL OR actor_id=$1) AND ($2::text IS NULL OR entity_type=$2) AND ($3::uuid IS NULL OR entity_id=$3) AND ($4::text IS NULL OR action=$4) AND ($5::timestamptz IS NULL OR created_at>=$5) AND ($6::timestamptz IS NULL OR created_at<=$6)
`

type CountAuditLogsParams struct {
	ActorID    *uuid.UUID  `json:"actor_id"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   *uuid.UUID  `json:"entity_id"`
	Action     pgtype.Text `json:"action"`
	FromTime   *time.Time  `json:"from_time"`
	ToTime     *time.Time  `json:"to_time"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTier3Application = `-- name: CreateTier3Application :one
INSERT INTO tier3_applications (id,user_id,status,nin_status,address_status,location_status,utility_document_status,address_text,address_line1,address_line2,city,state,country_code,postal_code,latitude,longitude,accuracy_meters,location_provider,location_mocked,location_captured_at,location_consent_at,reverse_geocoded_address,distance_meters,submitted_at,approved_at,reviewed_at,reviewed_by,rejection_reason,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30) RETURNING id, user_id, status, nin_status, address_status, location_status, utility_document_status, address_text, address_line1, address_line2, city, state, country_code, postal_code, latitude, longitude, accuracy_meters, location_provider, location_mocked, location_captured_at, location_consent_at, reverse_geocoded_address, distance_meters, submitted_at, approved_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at
`

type CreateTier3ApplicationParams struct {
	ID                     uuid.UUID     `json:"id"`
	UserID                 uuid.UUID     `json:"user_id"`
	Status                 string        `json:"status"`
	NinStatus              string        `json:"nin_status"`
	AddressStatus          string        `json:"address_status"`
	LocationStatus         string        `json:"location_status"`
	UtilityDocumentStatus  string        `json:"utility_document_status"`
	AddressText            pgtype.Text   `json:"address_text"`
	AddressLine1           pgtype.Text   `json:"address_line1"`
	AddressLine2           pgtype.Text   `json:"address_line2"`
	City                   pgtype.Text   `json:"city"`
	State                  pgtype.Text   `json:"state"`
	CountryCode            string        `json:"country_code"`
	PostalCode             pgtype.Text   `json:"postal_code"`
	Latitude               pgtype.Float8 `json:"latitude"`
	Longitude              pgtype.Float8 `json:"longitude"`
	AccuracyMeters         pgtype.Float8 `json:"accuracy_meters"`
	LocationProvider       pgtype.Text   `json:"location_provider"`
	LocationMocked         bool          `json:"location_mocked"`
	LocationCapturedAt     *time.Time    `json:"location_captured_at"`
	LocationConsentAt      *time.Time    `json:"location_consent_at"`
	ReverseGeocodedAddress pgtype.Text   `json:"reverse_geocoded_address"`
	DistanceMeters         pgtype.Float8 `json:"distance_meters"`
	SubmittedAt            *time.Time    `json:"submitted_at"`
	ApprovedAt             *time.Time    `json:"approved_at"`
	ReviewedAt             *time.Time    `json:"reviewed_at"`
	ReviewedBy             *uuid.UUID    `json:"reviewed_by"`
	RejectionReason        pgtype.Text   `json:"rejection_reason"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at"`
}

func (q *Queries) CreateTier3Application(ctx context.Context, arg CreateTier3ApplicationParams) (Tier3Application, error) {
	row := q.db.QueryRow(ctx, createTier3Application,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.NinStatus,
		arg.AddressStatus,
		arg.LocationStatus,
		arg.UtilityDocumentStatus,
		arg.AddressText,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.CountryCode,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyMeters,
		arg.LocationProvider,
		arg.LocationMocked,
		arg.LocationCapturedAt,
		arg.LocationConsentAt,
		arg.ReverseGeocodedAddress,
		arg.DistanceMeters,
		arg.SubmittedAt,
		arg.ApprovedAt,
		arg.ReviewedAt,
		arg.ReviewedBy,
		arg.RejectionReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tier3Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NinStatus,
		&i.AddressStatus,
		&i.LocationStatus,
		&i.UtilityDocumentStatus,
		&i.AddressText,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.CountryCode,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.AccuracyMeters,
		&i.LocationProvider,
		&i.LocationMocked,
		&i.LocationCapturedAt,
		&i.LocationConsentAt,
		&i.ReverseGeocodedAddress,
		&i.DistanceMeters,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTier3Document = `-- name: CreateTier3Document :one
INSERT INTO tier3_documents (id,application_id,user_id,document_type,original_filename,issue_date,object_key,content_type,size_bytes,sha256,etag,upload_expires_at,uploaded_at,extracted_name,extracted_address,status,rejection_reason,created_at,reviewed_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING id, application_id, user_id, document_type, original_filename, issue_date, object_key, content_type, size_bytes, sha256, etag, upload_expires_at, uploaded_at, extracted_name, extracted_address, status, rejection_reason, created_at, reviewed_at
`

type CreateTier3DocumentParams struct {
	ID               uuid.UUID   `json:"id"`
	ApplicationID    uuid.UUID   `json:"application_id"`
	UserID           uuid.UUID   `json:"user_id"`
	DocumentType     string      `json:"document_type"`
	OriginalFilename string      `json:"original_filename"`
	IssueDate        time.Time   `json:"issue_date"`
	ObjectKey        string      `json:"object_key"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	Sha256           string      `json:"sha256"`
	Etag             pgtype.Text `json:"etag"`
	UploadExpiresAt  *time.Time  `json:"upload_expires_at"`
	UploadedAt       *time.Time  `json:"uploaded_at"`
	ExtractedName    pgtype.Text `json:"extracted_name"`
	ExtractedAddress pgtype.Text `json:"extracted_address"`
	Status           string      `json:"status"`
	RejectionReason  pgtype.Text `json:"rejection_reason"`
	CreatedAt        time.Time   `json:"created_at"`
	ReviewedAt       *time.Time  `json:"reviewed_at"`
}

func (q *Queries) CreateTier3Document(ctx context.Context, arg CreateTier3DocumentParams) (Tier3Document, error) {
	row := q.db.QueryRow(ctx, createTier3Document,
		arg.ID,
		arg.ApplicationID,
		arg.UserID,
		arg.DocumentType,
		arg.OriginalFilename,
		arg.IssueDate,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Etag,
		arg.UploadExpiresAt,
		arg.UploadedAt,
		arg.ExtractedName,
		arg.ExtractedAddress,
		arg.Status,
		arg.RejectionReason,
		arg.CreatedAt,
		arg.ReviewedAt,
	)
	var i Tier3Document
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.DocumentType,
		&i.OriginalFilename,
		&i.IssueDate,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.ExtractedName,
		&i.ExtractedAddress,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const deletePublishedOutboxBefore = `-- name: DeletePublishedOutboxBefore :execrows
DELETE FROM outbox_events WHERE status='published' AND published_at<$1
`

func (q *Queries) DeletePublishedOutboxBefore(ctx context.Context, publishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutboxBefore, publishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :one
INSERT INTO outbox_events (id,exchange,routing_key,event_type,aggregate_type,aggregate_id,payload,status,attempts,last_error,available_at,published_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id, exchange, routing_key, event_type, aggregate_type, aggregate_id, payload, status, attempts, last_error, available_at, published_at, created_at, updated_at
`

type EnqueueOutboxParams struct {
	ID            uuid.UUID       `json:"id"`
	Exchange      string          `json:"exchange"`
	RoutingKey    string          `json:"routing_key"`
	EventType     string          `json:"event_type"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	Payload       json.RawMessage `json:"payload"`
	Status        string          `json:"status"`
	Attempts      int32           `json:"attempts"`
	LastError     pgtype.Text     `json:"last_error"`
	AvailableAt   time.Time       `json:"available_at"`
	PublishedAt   *time.Time      `json:"published_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueOutbox,
		arg.ID,
		arg.Exchange,
		arg.RoutingKey,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.AvailableAt,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.RoutingKey,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxDeadLetter = `-- name: MarkOutboxDeadLetter :exec
UPDATE outbox_events SET status='dead_letter',attempts=attempts+1,last_error=$2,updated_at=now() WHERE id=$1
`

type MarkOutboxDeadLetterParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxDeadLetter(ctx context.Context, arg MarkOutboxDeadLetterParams) error {
	_, err := q.db.Exec(ctx, markOutboxDeadLetter, arg.ID, arg.LastError)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_events SET status='failed',attempts=attempts+1,last_error=$2,available_at=$3,updated_at=now() WHERE id=$1
`

type MarkOutboxFailedParams struct {
	ID          uuid.UUID   `json:"id"`
	LastError   pgtype.Text `json:"last_error"`
	AvailableAt time.Time   `json:"available_at"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError, arg.AvailableAt)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events SET status='published',published_at=$2,last_error='',updated_at=now() WHERE id=$1
`

type MarkOutboxPublishedParams struct {
	ID          uuid.UUID  `json:"id"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, arg.ID, arg.PublishedAt)
	return err
}

const pendingOutboxCount = `-- name: PendingOutboxCount :one
SELECT count(*) FROM outbox_events WHERE status='pending'
`

func (q *Queries) PendingOutboxCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, pendingOutboxCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordAuditLog = `-- name: RecordAuditLog :one
INSERT INTO audit_logs (id,actor_type,actor_id,action,entity_type,entity_id,before_state,after_state,request_id,ip_address,user_agent,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, actor_type, actor_id, action, entity_type, entity_id, before_state, after_state, request_id, ip_address, user_agent, created_at
`

type RecordAuditLogParams struct {
	ID          uuid.UUID   `json:"id"`
	ActorType   string      `json:"actor_type"`
	ActorID     *uuid.UUID  `json:"actor_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    *uuid.UUID  `json:"entity_id"`
	BeforeState []byte      `json:"before_state"`
	AfterState  []byte      `json:"after_state"`
	RequestID   pgtype.Text `json:"request_id"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, recordAuditLog,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
		arg.RequestID,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeState,
		&i.AfterState,
		&i.RequestID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const replayOutboxEvent = `-- name: ReplayOutboxEvent :exec
UPDATE outbox_events SET status='pending',attempts=0,last_error='',available_at=now(),published_at=NULL,updated_at=now() WHERE id=$1 AND status='dead_letter'
`

func (q *Queries) ReplayOutboxEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, replayOutboxEvent, id)
	return err
}

const searchAuditLogs = `-- name: SearchAuditLogs :many
SELECT id, actor_type, actor_id, action, entity_type, entity_id, before_state, after_state, request_id, ip_address, user_agent, created_at FROM audit_logs WHERE ($3::uuid IS NULL OR actor_id=$3) AND ($4::text IS NULL OR entity_type=$4) AND ($5::uuid IS NULL OR entity_id=$5) AND ($6::text IS NULL OR action=$6) AND ($7::timestamptz IS NULL OR created_at>=$7) AND ($8::timestamptz IS NULL OR created_at<=$8) ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type SearchAuditLogsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	ActorID    *uuid.UUID  `json:"actor_id"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   *uuid.UUID  `json:"entity_id"`
	Action     pgtype.Text `json:"action"`
	FromTime   *time.Time  `json:"from_time"`
	ToTime     *time.Time  `json:"to_time"`
}

func (q *Queries) SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, searchAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.RequestID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tier3ApplicationByUserID = `-- name: Tier3ApplicationByUserID :one
SELECT id, user_id, status, nin_status, address_status, location_status, utility_document_status, address_text, address_line1, address_line2, city, state, country_code, postal_code, latitude, longitude, accuracy_meters, location_provider, location_mocked, location_captured_at, location_consent_at, reverse_geocoded_address, distance_meters, submitted_at, approved_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at FROM tier3_applications WHERE user_id=$1
`

func (q *Queries) Tier3ApplicationByUserID(ctx context.Context, userID uuid.UUID) (Tier3Application, error) {
	row := q.db.QueryRow(ctx, tier3ApplicationByUserID, userID)
	var i Tier3Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NinStatus,
		&i.AddressStatus,
		&i.LocationStatus,
		&i.UtilityDocumentStatus,
		&i.AddressText,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.CountryCode,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.AccuracyMeters,
		&i.LocationProvider,
		&i.LocationMocked,
		&i.LocationCapturedAt,
		&i.LocationConsentAt,
		&i.ReverseGeocodedAddress,
		&i.DistanceMeters,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tier3DocumentByID = `-- name: Tier3DocumentByID :one
SELECT id, application_id, user_id, document_type, original_filename, issue_date, object_key, content_type, size_bytes, sha256, etag, upload_expires_at, uploaded_at, extracted_name, extracted_address, status, rejection_reason, created_at, reviewed_at FROM tier3_documents WHERE id=$1 AND user_id=$2
`

type Tier3DocumentByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) Tier3DocumentByID(ctx context.Context, arg Tier3DocumentByIDParams) (Tier3Document, error) {
	row := q.db.QueryRow(ctx, tier3DocumentByID, arg.ID, arg.UserID)
	var i Tier3Document
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.DocumentType,
		&i.OriginalFilename,
		&i.IssueDate,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.ExtractedName,
		&i.ExtractedAddress,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const updateTier3Application = `-- name: UpdateTier3Application :one
UPDATE tier3_applications SET status=$2,nin_status=$3,address_status=$4,location_status=$5,utility_document_status=$6,address_text=$7,address_line1=$8,address_line2=$9,city=$10,state=$11,country_code=$12,postal_code=$13,latitude=$14,longitude=$15,accuracy_meters=$16,location_provider=$17,location_mocked=$18,location_captured_at=$19,location_consent_at=$20,reverse_geocoded_address=$21,distance_meters=$22,submitted_at=$23,approved_at=$24,reviewed_at=$25,reviewed_by=$26,rejection_reason=$27,updated_at=now() WHERE id=$1 RETURNING id, user_id, status, nin_status, address_status, location_status, utility_document_status, address_text, address_line1, address_line2, city, state, country_code, postal_code, latitude, longitude, accuracy_meters, location_provider, location_mocked, location_captured_at, location_consent_at, reverse_geocoded_address, distance_meters, submitted_at, approved_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at
`

type UpdateTier3ApplicationParams struct {
	ID                     uuid.UUID     `json:"id"`
	Status                 string        `json:"status"`
	NinStatus              string        `json:"nin_status"`
	AddressStatus          string        `json:"address_status"`
	LocationStatus         string        `json:"location_status"`
	UtilityDocumentStatus  string        `json:"utility_document_status"`
	AddressText            pgtype.Text   `json:"address_text"`
	AddressLine1           pgtype.Text   `json:"address_line1"`
	AddressLine2           pgtype.Text   `json:"address_line2"`
	City                   pgtype.Text   `json:"city"`
	State                  pgtype.Text   `json:"state"`
	CountryCode            string        `json:"country_code"`
	PostalCode             pgtype.Text   `json:"postal_code"`
	Latitude               pgtype.Float8 `json:"latitude"`
	Longitude              pgtype.Float8 `json:"longitude"`
	AccuracyMeters         pgtype.Float8 `json:"accuracy_meters"`
	LocationProvider       pgtype.Text   `json:"location_provider"`
	LocationMocked         bool          `json:"location_mocked"`
	LocationCapturedAt     *time.Time    `json:"location_captured_at"`
	LocationConsentAt      *time.Time    `json:"location_consent_at"`
	ReverseGeocodedAddress pgtype.Text   `json:"reverse_geocoded_address"`
	DistanceMeters         pgtype.Float8 `json:"distance_meters"`
	SubmittedAt            *time.Time    `json:"submitted_at"`
	ApprovedAt             *time.Time    `json:"approved_at"`
	ReviewedAt             *time.Time    `json:"reviewed_at"`
	ReviewedBy             *uuid.UUID    `json:"reviewed_by"`
	RejectionReason        pgtype.Text   `json:"rejection_reason"`
}

func (q *Queries) UpdateTier3Application(ctx context.Context, arg UpdateTier3ApplicationParams) (Tier3Application, error) {
	row := q.db.QueryRow(ctx, updateTier3Application,
		arg.ID,
		arg.Status,
		arg.NinStatus,
		arg.AddressStatus,
		arg.LocationStatus,
		arg.UtilityDocumentStatus,
		arg.AddressText,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.CountryCode,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyMeters,
		arg.LocationProvider,
		arg.LocationMocked,
		arg.LocationCapturedAt,
		arg.LocationConsentAt,
		arg.ReverseGeocodedAddress,
		arg.DistanceMeters,
		arg.SubmittedAt,
		arg.ApprovedAt,
		arg.ReviewedAt,
		arg.ReviewedBy,
		arg.RejectionReason,
	)
	var i Tier3Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.NinStatus,
		&i.AddressStatus,
		&i.LocationStatus,
		&i.UtilityDocumentStatus,
		&i.AddressText,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.CountryCode,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.AccuracyMeters,
		&i.LocationProvider,
		&i.LocationMocked,
		&i.LocationCapturedAt,
		&i.LocationConsentAt,
		&i.ReverseGeocodedAddress,
		&i.DistanceMeters,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
