// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveWaitlistEntryByUsername(ctx context.Context, lower string) (WaitlistEntry, error)
	ApplyLimitUsageDelta(ctx context.Context, arg ApplyLimitUsageDeltaParams) (int64, error)
	AssessmentsByUserID(ctx context.Context, arg AssessmentsByUserIDParams) ([]RiskAssessment, error)
	AuthUserByEmail(ctx context.Context, lower string) (User, error)
	AuthUserByEmailIncludingDeleted(ctx context.Context, lower string) (User, error)
	AuthUserByID(ctx context.Context, id uuid.UUID) (User, error)
	AuthUserByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (User, error)
	AuthUserByPhoneIncludingDeleted(ctx context.Context, phoneNumber pgtype.Text) (User, error)
	ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]OutboxEvent, error)
	ConfirmWaitlistEntry(ctx context.Context, arg ConfirmWaitlistEntryParams) (WaitlistEntry, error)
	ConfirmedWaitlistEntryByEmail(ctx context.Context, lower string) (WaitlistEntry, error)
	ConsumeOTP(ctx context.Context, arg ConsumeOTPParams) (int64, error)
	ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error)
	CreateKYCAttempt(ctx context.Context, arg CreateKYCAttemptParams) (KycVerificationAttempt, error)
	CreateKYCFacialCapture(ctx context.Context, arg CreateKYCFacialCaptureParams) (KycFacialCapture, error)
	CreateKYCProfile(ctx context.Context, arg CreateKYCProfileParams) (KycProfile, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreatePIN(ctx context.Context, arg CreatePINParams) (TransactionPin, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTier3Application(ctx context.Context, arg CreateTier3ApplicationParams) (Tier3Application, error)
	CreateTier3Document(ctx context.Context, arg CreateTier3DocumentParams) (Tier3Document, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error)
	CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error)
	DeletePublishedOutboxBefore(ctx context.Context, publishedAt *time.Time) (int64, error)
	DeviceByFingerprint(ctx context.Context, arg DeviceByFingerprintParams) (UserDevice, error)
	DeviceByID(ctx context.Context, id uuid.UUID) (UserDevice, error)
	DevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error)
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (OutboxEvent, error)
	EnsureLimitUsage(ctx context.Context, arg EnsureLimitUsageParams) error
	ExpireStaleWaitlistByUsername(ctx context.Context, arg ExpireStaleWaitlistByUsernameParams) error
	ExpireWaitlistEntry(ctx context.Context, arg ExpireWaitlistEntryParams) error
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error)
	InvalidateOTPs(ctx context.Context, arg InvalidateOTPsParams) error
	InvalidateVerificationTokens(ctx context.Context, arg InvalidateVerificationTokensParams) error
	KYCAttemptsByUserID(ctx context.Context, arg KYCAttemptsByUserIDParams) ([]KycVerificationAttempt, error)
	KYCProfileByBVNHash(ctx context.Context, bvnHash pgtype.Text) (KycProfile, error)
	KYCProfileByNINHash(ctx context.Context, ninHash pgtype.Text) (KycProfile, error)
	KYCProfileByUserID(ctx context.Context, userID uuid.UUID) (KycProfile, error)
	LimitForTier(ctx context.Context, arg LimitForTierParams) (TransactionLimit, error)
	ListTransactionLimits(ctx context.Context) ([]TransactionLimit, error)
	LockLimitUsage(ctx context.Context, arg LockLimitUsageParams) (LimitUsage, error)
	LockPINByUserID(ctx context.Context, userID uuid.UUID) (TransactionPin, error)
	MarkOutboxDeadLetter(ctx context.Context, arg MarkOutboxDeadLetterParams) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	OTPByChallengeToken(ctx context.Context, challengeToken string) (OtpCode, error)
	PINByUserID(ctx context.Context, userID uuid.UUID) (TransactionPin, error)
	PendingOutboxCount(ctx context.Context) (int64, error)
	RecentKYCAttemptCount(ctx context.Context, arg RecentKYCAttemptCountParams) (int64, error)
	RecentOTPCount(ctx context.Context, arg RecentOTPCountParams) (int64, error)
	RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) (AuditLog, error)
	RecordOTPFailure(ctx context.Context, id uuid.UUID) error
	RecordPINFailure(ctx context.Context, arg RecordPINFailureParams) error
	RecordRiskAssessment(ctx context.Context, arg RecordRiskAssessmentParams) (RiskAssessment, error)
	RefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	ReplayOutboxEvent(ctx context.Context, id uuid.UUID) error
	ResetPINAttempts(ctx context.Context, arg ResetPINAttemptsParams) error
	RestoreUser(ctx context.Context, id uuid.UUID) (User, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error)
	RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) error
	RevokeUserRefreshTokens(ctx context.Context, arg RevokeUserRefreshTokensParams) error
	SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]AuditLog, error)
	SetDeviceBlocked(ctx context.Context, arg SetDeviceBlockedParams) error
	SetDeviceTrusted(ctx context.Context, arg SetDeviceTrustedParams) error
	SetFacialStatus(ctx context.Context, arg SetFacialStatusParams) (User, error)
	SetNINStatus(ctx context.Context, arg SetNINStatusParams) (User, error)
	SetOTP(ctx context.Context, arg SetOTPParams) (User, error)
	SetPassword(ctx context.Context, arg SetPasswordParams) (User, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	Tier3ApplicationByUserID(ctx context.Context, userID uuid.UUID) (Tier3Application, error)
	Tier3DocumentByID(ctx context.Context, arg Tier3DocumentByIDParams) (Tier3Document, error)
	TouchDevice(ctx context.Context, arg TouchDeviceParams) error
	UpdateAuthUser(ctx context.Context, arg UpdateAuthUserParams) (User, error)
	UpdateKYCProfile(ctx context.Context, arg UpdateKYCProfileParams) (KycProfile, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdatePINHash(ctx context.Context, arg UpdatePINHashParams) (int64, error)
	UpdateTier3Application(ctx context.Context, arg UpdateTier3ApplicationParams) (Tier3Application, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UserDevice, error)
	UpsertTransactionLimit(ctx context.Context, arg UpsertTransactionLimitParams) (TransactionLimit, error)
	UsageForWindow(ctx context.Context, arg UsageForWindowParams) (LimitUsage, error)
	UserByAccountNumber(ctx context.Context, accountNumber pgtype.Text) (User, error)
	UserByUsername(ctx context.Context, lower string) (User, error)
	VerificationTokenByHash(ctx context.Context, tokenHash string) (VerificationToken, error)
	VerifyPhone(ctx context.Context, id uuid.UUID) (User, error)
	WaitlistEntryByReservationTokenHash(ctx context.Context, reservationTokenHash string) (WaitlistEntry, error)
}

var _ Querier = (*Queries)(nil)
