// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assessmentsByUserID = `-- name: AssessmentsByUserID :many
SELECT id, user_id, operation, decision, score, triggered_rules, amount_minor, currency, device_id, ip_address, reference, created_at FROM risk_assessments WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2
`

type AssessmentsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) AssessmentsByUserID(ctx context.Context, arg AssessmentsByUserIDParams) ([]RiskAssessment, error) {
	rows, err := q.db.Query(ctx, assessmentsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskAssessment{}
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Operation,
			&i.Decision,
			&i.Score,
			&i.TriggeredRules,
			&i.AmountMinor,
			&i.Currency,
			&i.DeviceID,
			&i.IpAddress,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeOTP = `-- name: ConsumeOTP :execrows
UPDATE otp_codes SET consumed_at=$2 WHERE id=$1 AND consumed_at IS NULL AND expires_at>$2
`

type ConsumeOTPParams struct {
	ID         uuid.UUID  `json:"id"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) ConsumeOTP(ctx context.Context, arg ConsumeOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOTP, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (id,user_id,purpose,channel,destination,code_hash,challenge_token,failed_attempts,consumed_at,expires_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, user_id, purpose, channel, destination, code_hash, challenge_token, failed_attempts, consumed_at, expires_at, created_at
`

type CreateOTPParams struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Purpose        string     `json:"purpose"`
	Channel        string     `json:"channel"`
	Destination    string     `json:"destination"`
	CodeHash       string     `json:"code_hash"`
	ChallengeToken string     `json:"challenge_token"`
	FailedAttempts int32      `json:"failed_attempts"`
	ConsumedAt     *time.Time `json:"consumed_at"`
	ExpiresAt      time.Time  `json:"expires_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Channel,
		arg.Destination,
		arg.CodeHash,
		arg.ChallengeToken,
		arg.FailedAttempts,
		arg.ConsumedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.ChallengeToken,
		&i.FailedAttempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPIN = `-- name: CreatePIN :one
INSERT INTO transaction_pins (id,user_id,pin_hash,failed_attempts,locked_until,last_used_at,last_changed_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, user_id, pin_hash, failed_attempts, locked_until, last_used_at, last_changed_at, created_at, updated_at
`

type CreatePINParams struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	PinHash        string     `json:"pin_hash"`
	FailedAttempts int32      `json:"failed_attempts"`
	LockedUntil    *time.Time `json:"locked_until"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	LastChangedAt  time.Time  `json:"last_changed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) CreatePIN(ctx context.Context, arg CreatePINParams) (TransactionPin, error) {
	row := q.db.QueryRow(ctx, createPIN,
		arg.ID,
		arg.UserID,
		arg.PinHash,
		arg.FailedAttempts,
		arg.LockedUntil,
		arg.LastUsedAt,
		arg.LastChangedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TransactionPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PinHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastUsedAt,
		&i.LastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deviceByFingerprint = `-- name: DeviceByFingerprint :one
SELECT id, user_id, fingerprint, name, platform, push_token, app_version, os_version, device_model, trusted, blocked, last_ip, latitude, longitude, last_seen_at, trusted_at, created_at, updated_at FROM user_devices WHERE user_id=$1 AND fingerprint=$2
`

type DeviceByFingerprintParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Fingerprint string    `json:"fingerprint"`
}

func (q *Queries) DeviceByFingerprint(ctx context.Context, arg DeviceByFingerprintParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, deviceByFingerprint, arg.UserID, arg.Fingerprint)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fingerprint,
		&i.Name,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.Trusted,
		&i.Blocked,
		&i.LastIp,
		&i.Latitude,
		&i.Longitude,
		&i.LastSeenAt,
		&i.TrustedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deviceByID = `-- name: DeviceByID :one
SELECT id, user_id, fingerprint, name, platform, push_token, app_version, os_version, device_model, trusted, blocked, last_ip, latitude, longitude, last_seen_at, trusted_at, created_at, updated_at FROM user_devices WHERE id=$1
`

func (q *Queries) DeviceByID(ctx context.Context, id uuid.UUID) (UserDevice, error) {
	row := q.db.QueryRow(ctx, deviceByID, id)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fingerprint,
		&i.Name,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.Trusted,
		&i.Blocked,
		&i.LastIp,
		&i.Latitude,
		&i.Longitude,
		&i.LastSeenAt,
		&i.TrustedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const devicesByUserID = `-- name: DevicesByUserID :many
SELECT id, user_id, fingerprint, name, platform, push_token, app_version, os_version, device_model, trusted, blocked, last_ip, latitude, longitude, last_seen_at, trusted_at, created_at, updated_at FROM user_devices WHERE user_id=$1 ORDER BY last_seen_at DESC NULLS LAST
`

func (q *Queries) DevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, devicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDevice{}
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Fingerprint,
			&i.Name,
			&i.Platform,
			&i.PushToken,
			&i.AppVersion,
			&i.OsVersion,
			&i.DeviceModel,
			&i.Trusted,
			&i.Blocked,
			&i.LastIp,
			&i.Latitude,
			&i.Longitude,
			&i.LastSeenAt,
			&i.TrustedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invalidateOTPs = `-- name: InvalidateOTPs :exec
UPDATE otp_codes SET consumed_at=$3 WHERE user_id=$1 AND purpose=$2 AND consumed_at IS NULL
`

type InvalidateOTPsParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	Purpose    string     `json:"purpose"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) InvalidateOTPs(ctx context.Context, arg InvalidateOTPsParams) error {
	_, err := q.db.Exec(ctx, invalidateOTPs, arg.UserID, arg.Purpose, arg.ConsumedAt)
	return err
}

const lockPINByUserID = `-- name: LockPINByUserID :one
SELECT id, user_id, pin_hash, failed_attempts, locked_until, last_used_at, last_changed_at, created_at, updated_at FROM transaction_pins WHERE user_id=$1 FOR UPDATE
`

func (q *Queries) LockPINByUserID(ctx context.Context, userID uuid.UUID) (TransactionPin, error) {
	row := q.db.QueryRow(ctx, lockPINByUserID, userID)
	var i TransactionPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PinHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastUsedAt,
		&i.LastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const oTPByChallengeToken = `-- name: OTPByChallengeToken :one
SELECT id, user_id, purpose, channel, destination, code_hash, challenge_token, failed_attempts, consumed_at, expires_at, created_at FROM otp_codes WHERE challenge_token=$1
`

func (q *Queries) OTPByChallengeToken(ctx context.Context, challengeToken string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, oTPByChallengeToken, challengeToken)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.ChallengeToken,
		&i.FailedAttempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const pINByUserID = `-- name: PINByUserID :one
SELECT id, user_id, pin_hash, failed_attempts, locked_until, last_used_at, last_changed_at, created_at, updated_at FROM transaction_pins WHERE user_id=$1
`

func (q *Queries) PINByUserID(ctx context.Context, userID uuid.UUID) (TransactionPin, error) {
	row := q.db.QueryRow(ctx, pINByUserID, userID)
	var i TransactionPin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PinHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastUsedAt,
		&i.LastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recentOTPCount = `-- name: RecentOTPCount :one
SELECT count(*) FROM otp_codes WHERE user_id=$1 AND purpose=$2 AND created_at >= $3
`

type RecentOTPCountParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) RecentOTPCount(ctx context.Context, arg RecentOTPCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, recentOTPCount, arg.UserID, arg.Purpose, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordOTPFailure = `-- name: RecordOTPFailure :exec
UPDATE otp_codes SET failed_attempts=failed_attempts+1 WHERE id=$1
`

func (q *Queries) RecordOTPFailure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordOTPFailure, id)
	return err
}

const recordPINFailure = `-- name: RecordPINFailure :exec
UPDATE transaction_pins SET failed_attempts=failed_attempts+1,locked_until=$2,updated_at=now() WHERE id=$1
`

type RecordPINFailureParams struct {
	ID          uuid.UUID  `json:"id"`
	LockedUntil *time.Time `json:"locked_until"`
}

func (q *Queries) RecordPINFailure(ctx context.Context, arg RecordPINFailureParams) error {
	_, err := q.db.Exec(ctx, recordPINFailure, arg.ID, arg.LockedUntil)
	return err
}

const recordRiskAssessment = `-- name: RecordRiskAssessment :one
INSERT INTO risk_assessments (id,user_id,operation,decision,score,triggered_rules,amount_minor,currency,device_id,ip_address,reference,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, user_id, operation, decision, score, triggered_rules, amount_minor, currency, device_id, ip_address, reference, created_at
`

type RecordRiskAssessmentParams struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Operation      string      `json:"operation"`
	Decision       string      `json:"decision"`
	Score          int32       `json:"score"`
	TriggeredRules pgtype.Text `json:"triggered_rules"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       pgtype.Text `json:"currency"`
	DeviceID       *uuid.UUID  `json:"device_id"`
	IpAddress      pgtype.Text `json:"ip_address"`
	Reference      pgtype.Text `json:"reference"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) RecordRiskAssessment(ctx context.Context, arg RecordRiskAssessmentParams) (RiskAssessment, error) {
	row := q.db.QueryRow(ctx, recordRiskAssessment,
		arg.ID,
		arg.UserID,
		arg.Operation,
		arg.Decision,
		arg.Score,
		arg.TriggeredRules,
		arg.AmountMinor,
		arg.Currency,
		arg.DeviceID,
		arg.IpAddress,
		arg.Reference,
		arg.CreatedAt,
	)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Operation,
		&i.Decision,
		&i.Score,
		&i.TriggeredRules,
		&i.AmountMinor,
		&i.Currency,
		&i.DeviceID,
		&i.IpAddress,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const resetPINAttempts = `-- name: ResetPINAttempts :exec
UPDATE transaction_pins SET failed_attempts=0,locked_until=NULL,last_used_at=$2,updated_at=now() WHERE id=$1
`

type ResetPINAttemptsParams struct {
	ID         uuid.UUID  `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

func (q *Queries) ResetPINAttempts(ctx context.Context, arg ResetPINAttemptsParams) error {
	_, err := q.db.Exec(ctx, resetPINAttempts, arg.ID, arg.LastUsedAt)
	return err
}

const setDeviceBlocked = `-- name: SetDeviceBlocked :exec
UPDATE user_devices SET blocked=$2,updated_at=now() WHERE id=$1
`

type SetDeviceBlockedParams struct {
	ID      uuid.UUID `json:"id"`
	Blocked bool      `json:"blocked"`
}

func (q *Queries) SetDeviceBlocked(ctx context.Context, arg SetDeviceBlockedParams) error {
	_, err := q.db.Exec(ctx, setDeviceBlocked, arg.ID, arg.Blocked)
	return err
}

const setDeviceTrusted = `-- name: SetDeviceTrusted :exec
UPDATE user_devices SET trusted=$2,trusted_at=$3,updated_at=now() WHERE id=$1
`

type SetDeviceTrustedParams struct {
	ID        uuid.UUID  `json:"id"`
	Trusted   bool       `json:"trusted"`
	TrustedAt *time.Time `json:"trusted_at"`
}

func (q *Queries) SetDeviceTrusted(ctx context.Context, arg SetDeviceTrustedParams) error {
	_, err := q.db.Exec(ctx, setDeviceTrusted, arg.ID, arg.Trusted, arg.TrustedAt)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE user_devices SET last_ip=$2,last_seen_at=$3,updated_at=now() WHERE id=$1
`

type TouchDeviceParams struct {
	ID         uuid.UUID   `json:"id"`
	LastIp     pgtype.Text `json:"last_ip"`
	LastSeenAt *time.Time  `json:"last_seen_at"`
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice, arg.ID, arg.LastIp, arg.LastSeenAt)
	return err
}

const updatePINHash = `-- name: UpdatePINHash :execrows
UPDATE transaction_pins SET pin_hash=$2,failed_attempts=0,locked_until=NULL,last_changed_at=$3,updated_at=now() WHERE user_id=$1
`

type UpdatePINHashParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PinHash       string    `json:"pin_hash"`
	LastChangedAt time.Time `json:"last_changed_at"`
}

func (q *Queries) UpdatePINHash(ctx context.Context, arg UpdatePINHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePINHash, arg.UserID, arg.PinHash, arg.LastChangedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO user_devices (id,user_id,fingerprint,name,platform,push_token,app_version,os_version,device_model,trusted,blocked,last_ip,latitude,longitude,last_seen_at,trusted_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT (user_id,fingerprint) DO UPDATE SET name=excluded.name,platform=excluded.platform,push_token=excluded.push_token,app_version=excluded.app_version,os_version=excluded.os_version,device_model=excluded.device_model,last_ip=excluded.last_ip,latitude=excluded.latitude,longitude=excluded.longitude,last_seen_at=excluded.last_seen_at,updated_at=now() RETURNING id, user_id, fingerprint, name, platform, push_token, app_version, os_version, device_model, trusted, blocked, last_ip, latitude, longitude, last_seen_at, trusted_at, created_at, updated_at
`

type UpsertDeviceParams struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Fingerprint string        `json:"fingerprint"`
	Name        pgtype.Text   `json:"name"`
	Platform    pgtype.Text   `json:"platform"`
	PushToken   pgtype.Text   `json:"push_token"`
	AppVersion  pgtype.Text   `json:"app_version"`
	OsVersion   pgtype.Text   `json:"os_version"`
	DeviceModel pgtype.Text   `json:"device_model"`
	Trusted     bool          `json:"trusted"`
	Blocked     bool          `json:"blocked"`
	LastIp      pgtype.Text   `json:"last_ip"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	LastSeenAt  *time.Time    `json:"last_seen_at"`
	TrustedAt   *time.Time    `json:"trusted_at"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Fingerprint,
		arg.Name,
		arg.Platform,
		arg.PushToken,
		arg.AppVersion,
		arg.OsVersion,
		arg.DeviceModel,
		arg.Trusted,
		arg.Blocked,
		arg.LastIp,
		arg.Latitude,
		arg.Longitude,
		arg.LastSeenAt,
		arg.TrustedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fingerprint,
		&i.Name,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.Trusted,
		&i.Blocked,
		&i.LastIp,
		&i.Latitude,
		&i.Longitude,
		&i.LastSeenAt,
		&i.TrustedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
