// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, otp_code, otp_expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type CreateUserParams struct {
	PhoneNumber  pgtype.Text `json:"phone_number"`
	OtpCode      pgtype.Text `json:"otp_code"`
	OtpExpiresAt *time.Time  `json:"otp_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneNumber, arg.OtpCode, arg.OtpExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const setFacialStatus = `-- name: SetFacialStatus :one
UPDATE users SET facial_status = $2, facial_verified = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type SetFacialStatusParams struct {
	ID             uuid.UUID `json:"id"`
	FacialStatus   string    `json:"facial_status"`
	FacialVerified bool      `json:"facial_verified"`
}

func (q *Queries) SetFacialStatus(ctx context.Context, arg SetFacialStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setFacialStatus, arg.ID, arg.FacialStatus, arg.FacialVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const setNINStatus = `-- name: SetNINStatus :one
UPDATE users SET nin_status = $2, nin_verified = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type SetNINStatusParams struct {
	ID          uuid.UUID `json:"id"`
	NinStatus   string    `json:"nin_status"`
	NinVerified bool      `json:"nin_verified"`
}

func (q *Queries) SetNINStatus(ctx context.Context, arg SetNINStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setNINStatus, arg.ID, arg.NinStatus, arg.NinVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const setOTP = `-- name: SetOTP :one
UPDATE users SET otp_code = $2, otp_expires_at = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type SetOTPParams struct {
	ID           uuid.UUID   `json:"id"`
	OtpCode      pgtype.Text `json:"otp_code"`
	OtpExpiresAt *time.Time  `json:"otp_expires_at"`
}

func (q *Queries) SetOTP(ctx context.Context, arg SetOTPParams) (User, error) {
	row := q.db.QueryRow(ctx, setOTP, arg.ID, arg.OtpCode, arg.OtpExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const setPassword = `-- name: SetPassword :one
UPDATE users SET password_hash = $2, password_set = true, updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type SetPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET avatar_url = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

type UpdateUserAvatarParams struct {
	ID        uuid.UUID   `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const verifyPhone = `-- name: VerifyPhone :one
UPDATE users SET phone_verified = true, phone_verified_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url
`

func (q *Queries) VerifyPhone(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyPhone, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}
