// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeWaitlistEntryByUsername = `-- name: ActiveWaitlistEntryByUsername :one
SELECT id, nablr_username, email, reservation_token_hash, status, held_at, hold_expires_at, confirmed_at, expires_at, claimed_user_id, claimed_at, requested_ip, user_agent, created_at, updated_at FROM waitlist_entries WHERE lower(nablr_username)=lower($1) AND status IN ('held','confirmed')
`

func (q *Queries) ActiveWaitlistEntryByUsername(ctx context.Context, lower string) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, activeWaitlistEntryByUsername, lower)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.NablrUsername,
		&i.Email,
		&i.ReservationTokenHash,
		&i.Status,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.ClaimedUserID,
		&i.ClaimedAt,
		&i.RequestedIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmWaitlistEntry = `-- name: ConfirmWaitlistEntry :one
UPDATE waitlist_entries SET email=$2, status='confirmed', confirmed_at=$3, expires_at=$4, updated_at=$3
WHERE id=$1 AND status='held' RETURNING id, nablr_username, email, reservation_token_hash, status, held_at, hold_expires_at, confirmed_at, expires_at, claimed_user_id, claimed_at, requested_ip, user_agent, created_at, updated_at
`

type ConfirmWaitlistEntryParams struct {
	ID          uuid.UUID   `json:"id"`
	Email       pgtype.Text `json:"email"`
	ConfirmedAt *time.Time  `json:"confirmed_at"`
	ExpiresAt   *time.Time  `json:"expires_at"`
}

func (q *Queries) ConfirmWaitlistEntry(ctx context.Context, arg ConfirmWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, confirmWaitlistEntry,
		arg.ID,
		arg.Email,
		arg.ConfirmedAt,
		arg.ExpiresAt,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.NablrUsername,
		&i.Email,
		&i.ReservationTokenHash,
		&i.Status,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.ClaimedUserID,
		&i.ClaimedAt,
		&i.RequestedIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmedWaitlistEntryByEmail = `-- name: ConfirmedWaitlistEntryByEmail :one
SELECT id, nablr_username, email, reservation_token_hash, status, held_at, hold_expires_at, confirmed_at, expires_at, claimed_user_id, claimed_at, requested_ip, user_agent, created_at, updated_at FROM waitlist_entries WHERE lower(email)=lower($1) AND status='confirmed'
`

func (q *Queries) ConfirmedWaitlistEntryByEmail(ctx context.Context, lower string) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, confirmedWaitlistEntryByEmail, lower)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.NablrUsername,
		&i.Email,
		&i.ReservationTokenHash,
		&i.Status,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.ClaimedUserID,
		&i.ClaimedAt,
		&i.RequestedIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist_entries (id,nablr_username,reservation_token_hash,status,held_at,hold_expires_at,requested_ip,user_agent,created_at,updated_at)
VALUES ($1,$2,$3,'held',$4,$5,$6,$7,$4,$4) RETURNING id, nablr_username, email, reservation_token_hash, status, held_at, hold_expires_at, confirmed_at, expires_at, claimed_user_id, claimed_at, requested_ip, user_agent, created_at, updated_at
`

type CreateWaitlistEntryParams struct {
	ID                   uuid.UUID   `json:"id"`
	NablrUsername        string      `json:"nablr_username"`
	ReservationTokenHash string      `json:"reservation_token_hash"`
	HeldAt               time.Time   `json:"held_at"`
	HoldExpiresAt        time.Time   `json:"hold_expires_at"`
	RequestedIp          pgtype.Text `json:"requested_ip"`
	UserAgent            pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, createWaitlistEntry,
		arg.ID,
		arg.NablrUsername,
		arg.ReservationTokenHash,
		arg.HeldAt,
		arg.HoldExpiresAt,
		arg.RequestedIp,
		arg.UserAgent,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.NablrUsername,
		&i.Email,
		&i.ReservationTokenHash,
		&i.Status,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.ClaimedUserID,
		&i.ClaimedAt,
		&i.RequestedIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleWaitlistByUsername = `-- name: ExpireStaleWaitlistByUsername :exec
UPDATE waitlist_entries SET status='expired', updated_at=now()
WHERE lower(nablr_username)=lower($1) AND status IN ('held','confirmed')
  AND ((status='held' AND hold_expires_at<=$2) OR (status='confirmed' AND expires_at<=$2))
`

type ExpireStaleWaitlistByUsernameParams struct {
	Lower         string    `json:"lower"`
	HoldExpiresAt time.Time `json:"hold_expires_at"`
}

func (q *Queries) ExpireStaleWaitlistByUsername(ctx context.Context, arg ExpireStaleWaitlistByUsernameParams) error {
	_, err := q.db.Exec(ctx, expireStaleWaitlistByUsername, arg.Lower, arg.HoldExpiresAt)
	return err
}

const expireWaitlistEntry = `-- name: ExpireWaitlistEntry :exec
UPDATE waitlist_entries SET status='expired', updated_at=$2 WHERE id=$1
`

type ExpireWaitlistEntryParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ExpireWaitlistEntry(ctx context.Context, arg ExpireWaitlistEntryParams) error {
	_, err := q.db.Exec(ctx, expireWaitlistEntry, arg.ID, arg.UpdatedAt)
	return err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, email, phone_number, nablr_username, password_hash, password_set, role, status, phone_verified, phone_verified_at, otp_code, otp_expires_at, nin_status, nin_verified, facial_status, facial_verified, email_verified_at, last_login_at, deleted_at, created_at, updated_at, account_number, avatar_url FROM users WHERE lower(nablr_username)=lower($1) AND deleted_at IS NULL
`

func (q *Queries) UserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, userByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.NablrUsername,
		&i.PasswordHash,
		&i.PasswordSet,
		&i.Role,
		&i.Status,
		&i.PhoneVerified,
		&i.PhoneVerifiedAt,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.NinStatus,
		&i.NinVerified,
		&i.FacialStatus,
		&i.FacialVerified,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumber,
		&i.AvatarUrl,
	)
	return i, err
}

const waitlistEntryByReservationTokenHash = `-- name: WaitlistEntryByReservationTokenHash :one
SELECT id, nablr_username, email, reservation_token_hash, status, held_at, hold_expires_at, confirmed_at, expires_at, claimed_user_id, claimed_at, requested_ip, user_agent, created_at, updated_at FROM waitlist_entries WHERE reservation_token_hash=$1
`

func (q *Queries) WaitlistEntryByReservationTokenHash(ctx context.Context, reservationTokenHash string) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, waitlistEntryByReservationTokenHash, reservationTokenHash)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.NablrUsername,
		&i.Email,
		&i.ReservationTokenHash,
		&i.Status,
		&i.HeldAt,
		&i.HoldExpiresAt,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.ClaimedUserID,
		&i.ClaimedAt,
		&i.RequestedIp,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
