// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceToken struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	Provider   string      `json:"provider"`
	Platform   pgtype.Text `json:"platform"`
	LastUsedAt *time.Time  `json:"last_used_at"`
	RevokedAt  *time.Time  `json:"revoked_at"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type NotificationDeliveryAttempt struct {
	ID                uuid.UUID   `json:"id"`
	RequestID         pgtype.Text `json:"request_id"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	UserID            *uuid.UUID  `json:"user_id"`
	Channel           string      `json:"channel"`
	Provider          string      `json:"provider"`
	TemplateCode      pgtype.Text `json:"template_code"`
	DestinationHash   pgtype.Text `json:"destination_hash"`
	DestinationMasked pgtype.Text `json:"destination_masked"`
	Subject           pgtype.Text `json:"subject"`
	Status            string      `json:"status"`
	ProviderReference pgtype.Text `json:"provider_reference"`
	ErrorCode         pgtype.Text `json:"error_code"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	Payload           []byte      `json:"payload"`
	SentAt            *time.Time  `json:"sent_at"`
	FailedAt          *time.Time  `json:"failed_at"`
	NextRetryAt       *time.Time  `json:"next_retry_at"`
	AttemptCount      int32       `json:"attempt_count"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type NotificationEvent struct {
	ID          uuid.UUID       `json:"id"`
	AggregateID *uuid.UUID      `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
	Status      string          `json:"status"`
	Attempts    int32           `json:"attempts"`
	LastError   pgtype.Text     `json:"last_error"`
	AvailableAt time.Time       `json:"available_at"`
	PublishedAt *time.Time      `json:"published_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type NotificationPreference struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Channel   string    `json:"channel"`
	Category  string    `json:"category"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationProviderStatus struct {
	Provider      string      `json:"provider"`
	Channel       string      `json:"channel"`
	Status        string      `json:"status"`
	SuccessCount  int64       `json:"success_count"`
	FailureCount  int64       `json:"failure_count"`
	LastSuccessAt *time.Time  `json:"last_success_at"`
	LastFailureAt *time.Time  `json:"last_failure_at"`
	LastError     pgtype.Text `json:"last_error"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type NotificationTemplate struct {
	ID        uuid.UUID   `json:"id"`
	Code      string      `json:"code"`
	Channel   string      `json:"channel"`
	Subject   pgtype.Text `json:"subject"`
	BodyText  pgtype.Text `json:"body_text"`
	BodyHtml  pgtype.Text `json:"body_html"`
	Locale    string      `json:"locale"`
	Active    bool        `json:"active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
