// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package notificationdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeDeviceTokensByUser = `-- name: ActiveDeviceTokensByUser :many
SELECT id, user_id, token_hash, provider, platform, last_used_at, revoked_at, created_at, updated_at
FROM device_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY COALESCE(last_used_at, created_at) DESC
`

func (q *Queries) ActiveDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, activeDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Provider,
			&i.Platform,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRetryableDeliveryAttempts = `-- name: ClaimRetryableDeliveryAttempts :many
SELECT id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
FROM notification_delivery_attempts
WHERE status IN ('queued', 'retrying')
  AND (next_retry_at IS NULL OR next_retry_at <= $1)
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimRetryableDeliveryAttemptsParams struct {
	NextRetryAt *time.Time `json:"next_retry_at"`
	Limit       int32      `json:"limit"`
}

func (q *Queries) ClaimRetryableDeliveryAttempts(ctx context.Context, arg ClaimRetryableDeliveryAttemptsParams) ([]NotificationDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, claimRetryableDeliveryAttempts, arg.NextRetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDeliveryAttempt{}
	for rows.Next() {
		var i NotificationDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.UserID,
			&i.Channel,
			&i.Provider,
			&i.TemplateCode,
			&i.DestinationHash,
			&i.DestinationMasked,
			&i.Subject,
			&i.Status,
			&i.ProviderReference,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.SentAt,
			&i.FailedAt,
			&i.NextRetryAt,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUnpublishedNotificationEvents = `-- name: ClaimUnpublishedNotificationEvents :many
WITH claimed AS (
    SELECT id FROM notification_events
    WHERE status IN ('pending', 'failed') AND available_at <= now()
    ORDER BY available_at, created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE notification_events event
SET status = 'processing', attempts = attempts + 1
FROM claimed
WHERE event.id = claimed.id
RETURNING event.id, event.aggregate_id, event.event_type, event.payload, event.status, event.attempts, event.last_error, event.available_at, event.published_at, event.created_at
`

func (q *Queries) ClaimUnpublishedNotificationEvents(ctx context.Context, limit int32) ([]NotificationEvent, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedNotificationEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.AvailableAt,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO notification_delivery_attempts (
    id,
    request_id,
    idempotency_key,
    user_id,
    channel,
    provider,
    template_code,
    destination_hash,
    destination_masked,
    subject,
    status,
    provider_reference,
    error_code,
    error_message,
    payload,
    sent_at,
    failed_at,
    next_retry_at,
    attempt_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
`

type CreateDeliveryAttemptParams struct {
	ID                uuid.UUID   `json:"id"`
	RequestID         pgtype.Text `json:"request_id"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	UserID            *uuid.UUID  `json:"user_id"`
	Channel           string      `json:"channel"`
	Provider          string      `json:"provider"`
	TemplateCode      pgtype.Text `json:"template_code"`
	DestinationHash   pgtype.Text `json:"destination_hash"`
	DestinationMasked pgtype.Text `json:"destination_masked"`
	Subject           pgtype.Text `json:"subject"`
	Status            string      `json:"status"`
	ProviderReference pgtype.Text `json:"provider_reference"`
	ErrorCode         pgtype.Text `json:"error_code"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	Payload           []byte      `json:"payload"`
	SentAt            *time.Time  `json:"sent_at"`
	FailedAt          *time.Time  `json:"failed_at"`
	NextRetryAt       *time.Time  `json:"next_retry_at"`
	AttemptCount      int32       `json:"attempt_count"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.ID,
		arg.RequestID,
		arg.IdempotencyKey,
		arg.UserID,
		arg.Channel,
		arg.Provider,
		arg.TemplateCode,
		arg.DestinationHash,
		arg.DestinationMasked,
		arg.Subject,
		arg.Status,
		arg.ProviderReference,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Payload,
		arg.SentAt,
		arg.FailedAt,
		arg.NextRetryAt,
		arg.AttemptCount,
	)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationEvent = `-- name: CreateNotificationEvent :one
INSERT INTO notification_events (
    id,
    aggregate_id,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
) RETURNING id, aggregate_id, event_type, payload, status, attempts, last_error, available_at, published_at, created_at
`

type CreateNotificationEventParams struct {
	ID          uuid.UUID       `json:"id"`
	AggregateID *uuid.UUID      `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, createNotificationEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationTemplate = `-- name: CreateNotificationTemplate :one
INSERT INTO notification_templates (
    id,
    code,
    channel,
    subject,
    body_text,
    body_html,
    locale,
    active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, code, channel, subject, body_text, body_html, locale, active, created_at, updated_at
`

type CreateNotificationTemplateParams struct {
	ID       uuid.UUID   `json:"id"`
	Code     string      `json:"code"`
	Channel  string      `json:"channel"`
	Subject  pgtype.Text `json:"subject"`
	BodyText pgtype.Text `json:"body_text"`
	BodyHtml pgtype.Text `json:"body_html"`
	Locale   string      `json:"locale"`
	Active   bool        `json:"active"`
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createNotificationTemplate,
		arg.ID,
		arg.Code,
		arg.Channel,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.Locale,
		arg.Active,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Locale,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deadLetterNotificationEvent = `-- name: DeadLetterNotificationEvent :exec
UPDATE notification_events
SET status = 'dead_letter', last_error = $2
WHERE id = $1
`

type DeadLetterNotificationEventParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) DeadLetterNotificationEvent(ctx context.Context, arg DeadLetterNotificationEventParams) error {
	_, err := q.db.Exec(ctx, deadLetterNotificationEvent, arg.ID, arg.LastError)
	return err
}

const deliveryAttemptByID = `-- name: DeliveryAttemptByID :one
SELECT id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
FROM notification_delivery_attempts
WHERE id = $1
`

func (q *Queries) DeliveryAttemptByID(ctx context.Context, id uuid.UUID) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, deliveryAttemptByID, id)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deliveryAttemptByIdempotencyKey = `-- name: DeliveryAttemptByIdempotencyKey :one
SELECT id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
FROM notification_delivery_attempts
WHERE idempotency_key = $1
`

func (q *Queries) DeliveryAttemptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, deliveryAttemptByIdempotencyKey, idempotencyKey)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveryAttemptsByUser = `-- name: ListDeliveryAttemptsByUser :many
SELECT id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
FROM notification_delivery_attempts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveryAttemptsByUserParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListDeliveryAttemptsByUser(ctx context.Context, arg ListDeliveryAttemptsByUserParams) ([]NotificationDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDeliveryAttempt{}
	for rows.Next() {
		var i NotificationDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.UserID,
			&i.Channel,
			&i.Provider,
			&i.TemplateCode,
			&i.DestinationHash,
			&i.DestinationMasked,
			&i.Subject,
			&i.Status,
			&i.ProviderReference,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.SentAt,
			&i.FailedAt,
			&i.NextRetryAt,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPreferencesByUser = `-- name: ListNotificationPreferencesByUser :many
SELECT id, user_id, channel, category, enabled, created_at, updated_at
FROM notification_preferences
WHERE user_id = $1
ORDER BY channel, category
`

func (q *Queries) ListNotificationPreferencesByUser(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Category,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationTemplates = `-- name: ListNotificationTemplates :many
SELECT id, code, channel, subject, body_text, body_html, locale, active, created_at, updated_at
FROM notification_templates
WHERE ($3::text IS NULL OR channel = $3)
  AND ($4::text IS NULL OR locale = $4)
  AND ($5::boolean IS NULL OR active = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationTemplatesParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Channel pgtype.Text `json:"channel"`
	Locale  pgtype.Text `json:"locale"`
	Active  pgtype.Bool `json:"active"`
}

func (q *Queries) ListNotificationTemplates(ctx context.Context, arg ListNotificationTemplatesParams) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listNotificationTemplates,
		arg.Limit,
		arg.Offset,
		arg.Channel,
		arg.Locale,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Channel,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtml,
			&i.Locale,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryAttemptFailed = `-- name: MarkDeliveryAttemptFailed :one
UPDATE notification_delivery_attempts
SET status = $2,
    error_code = $3,
    error_message = $4,
    failed_at = now(),
    next_retry_at = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
`

type MarkDeliveryAttemptFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	NextRetryAt  *time.Time  `json:"next_retry_at"`
}

func (q *Queries) MarkDeliveryAttemptFailed(ctx context.Context, arg MarkDeliveryAttemptFailedParams) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, markDeliveryAttemptFailed,
		arg.ID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.NextRetryAt,
	)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryAttemptSending = `-- name: MarkDeliveryAttemptSending :one
UPDATE notification_delivery_attempts
SET status = 'sending',
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
`

func (q *Queries) MarkDeliveryAttemptSending(ctx context.Context, id uuid.UUID) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, markDeliveryAttemptSending, id)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryAttemptSent = `-- name: MarkDeliveryAttemptSent :one
UPDATE notification_delivery_attempts
SET status = 'sent',
    provider_reference = $2,
    sent_at = now(),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, idempotency_key, user_id, channel, provider, template_code, destination_hash, destination_masked, subject, status, provider_reference, error_code, error_message, payload, sent_at, failed_at, next_retry_at, attempt_count, created_at, updated_at
`

type MarkDeliveryAttemptSentParams struct {
	ID                uuid.UUID   `json:"id"`
	ProviderReference pgtype.Text `json:"provider_reference"`
}

func (q *Queries) MarkDeliveryAttemptSent(ctx context.Context, arg MarkDeliveryAttemptSentParams) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, markDeliveryAttemptSent, arg.ID, arg.ProviderReference)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.Channel,
		&i.Provider,
		&i.TemplateCode,
		&i.DestinationHash,
		&i.DestinationMasked,
		&i.Subject,
		&i.Status,
		&i.ProviderReference,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.SentAt,
		&i.FailedAt,
		&i.NextRetryAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationEventFailed = `-- name: MarkNotificationEventFailed :exec
UPDATE notification_events
SET status = 'failed', last_error = $2, available_at = $3
WHERE id = $1
`

type MarkNotificationEventFailedParams struct {
	ID          uuid.UUID   `json:"id"`
	LastError   pgtype.Text `json:"last_error"`
	AvailableAt time.Time   `json:"available_at"`
}

func (q *Queries) MarkNotificationEventFailed(ctx context.Context, arg MarkNotificationEventFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationEventFailed, arg.ID, arg.LastError, arg.AvailableAt)
	return err
}

const markNotificationEventPublished = `-- name: MarkNotificationEventPublished :execrows
UPDATE notification_events
SET status = 'published', published_at = now(), last_error = NULL
WHERE id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkNotificationEventPublished(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationEventPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationPreference = `-- name: NotificationPreference :one
SELECT id, user_id, channel, category, enabled, created_at, updated_at
FROM notification_preferences
WHERE user_id = $1
  AND channel = $2
  AND category = $3
`

type NotificationPreferenceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Channel  string    `json:"channel"`
	Category string    `json:"category"`
}

func (q *Queries) NotificationPreference(ctx context.Context, arg NotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, notificationPreference, arg.UserID, arg.Channel, arg.Category)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Category,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationTemplateByCode = `-- name: NotificationTemplateByCode :one
SELECT id, code, channel, subject, body_text, body_html, locale, active, created_at, updated_at
FROM notification_templates
WHERE code = $1
  AND channel = $2
  AND locale = $3
  AND active = true
`

type NotificationTemplateByCodeParams struct {
	Code    string `json:"code"`
	Channel string `json:"channel"`
	Locale  string `json:"locale"`
}

func (q *Queries) NotificationTemplateByCode(ctx context.Context, arg NotificationTemplateByCodeParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, notificationTemplateByCode, arg.Code, arg.Channel, arg.Locale)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Locale,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const providerStatus = `-- name: ProviderStatus :one
SELECT provider, channel, status, success_count, failure_count, last_success_at, last_failure_at, last_error, updated_at
FROM notification_provider_status
WHERE provider = $1
  AND channel = $2
`

type ProviderStatusParams struct {
	Provider string `json:"provider"`
	Channel  string `json:"channel"`
}

func (q *Queries) ProviderStatus(ctx context.Context, arg ProviderStatusParams) (NotificationProviderStatus, error) {
	row := q.db.QueryRow(ctx, providerStatus, arg.Provider, arg.Channel)
	var i NotificationProviderStatus
	err := row.Scan(
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDeviceToken = `-- name: RevokeDeviceToken :execrows
UPDATE device_tokens
SET revoked_at = now(),
    updated_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeDeviceToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotificationTemplate = `-- name: UpdateNotificationTemplate :one
UPDATE notification_templates
SET
    code = $2,
    channel = $3,
    subject = $4,
    body_text = $5,
    body_html = $6,
    locale = $7,
    active = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, code, channel, subject, body_text, body_html, locale, active, created_at, updated_at
`

type UpdateNotificationTemplateParams struct {
	ID       uuid.UUID   `json:"id"`
	Code     string      `json:"code"`
	Channel  string      `json:"channel"`
	Subject  pgtype.Text `json:"subject"`
	BodyText pgtype.Text `json:"body_text"`
	BodyHtml pgtype.Text `json:"body_html"`
	Locale   string      `json:"locale"`
	Active   bool        `json:"active"`
}

func (q *Queries) UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, updateNotificationTemplate,
		arg.ID,
		arg.Code,
		arg.Channel,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.Locale,
		arg.Active,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Channel,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Locale,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (
    id,
    user_id,
    token_hash,
    provider,
    platform,
    last_used_at,
    revoked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (token_hash)
DO UPDATE SET
    user_id = EXCLUDED.user_id,
    provider = EXCLUDED.provider,
    platform = EXCLUDED.platform,
    last_used_at = COALESCE(EXCLUDED.last_used_at, now()),
    revoked_at = NULL,
    updated_at = now()
RETURNING id, user_id, token_hash, provider, platform, last_used_at, revoked_at, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	Provider   string      `json:"provider"`
	Platform   pgtype.Text `json:"platform"`
	LastUsedAt *time.Time  `json:"last_used_at"`
	RevokedAt  *time.Time  `json:"revoked_at"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Provider,
		arg.Platform,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Provider,
		&i.Platform,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (
    id,
    user_id,
    channel,
    category,
    enabled
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (user_id, channel, category)
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, user_id, channel, category, enabled, created_at, updated_at
`

type UpsertNotificationPreferenceParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Channel  string    `json:"channel"`
	Category string    `json:"category"`
	Enabled  bool      `json:"enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Category,
		arg.Enabled,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Category,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderStatus = `-- name: UpsertProviderStatus :one
INSERT INTO notification_provider_status (
    provider,
    channel,
    status,
    success_count,
    failure_count,
    last_success_at,
    last_failure_at,
    last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (provider, channel)
DO UPDATE SET
    status = EXCLUDED.status,
    success_count = notification_provider_status.success_count + EXCLUDED.success_count,
    failure_count = notification_provider_status.failure_count + EXCLUDED.failure_count,
    last_success_at = COALESCE(EXCLUDED.last_success_at, notification_provider_status.last_success_at),
    last_failure_at = COALESCE(EXCLUDED.last_failure_at, notification_provider_status.last_failure_at),
    last_error = EXCLUDED.last_error,
    updated_at = now()
RETURNING provider, channel, status, success_count, failure_count, last_success_at, last_failure_at, last_error, updated_at
`

type UpsertProviderStatusParams struct {
	Provider      string      `json:"provider"`
	Channel       string      `json:"channel"`
	Status        string      `json:"status"`
	SuccessCount  int64       `json:"success_count"`
	FailureCount  int64       `json:"failure_count"`
	LastSuccessAt *time.Time  `json:"last_success_at"`
	LastFailureAt *time.Time  `json:"last_failure_at"`
	LastError     pgtype.Text `json:"last_error"`
}

func (q *Queries) UpsertProviderStatus(ctx context.Context, arg UpsertProviderStatusParams) (NotificationProviderStatus, error) {
	row := q.db.QueryRow(ctx, upsertProviderStatus,
		arg.Provider,
		arg.Channel,
		arg.Status,
		arg.SuccessCount,
		arg.FailureCount,
		arg.LastSuccessAt,
		arg.LastFailureAt,
		arg.LastError,
	)
	var i NotificationProviderStatus
	err := row.Scan(
		&i.Provider,
		&i.Channel,
		&i.Status,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}
