// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ClaimRetryableDeliveryAttempts(ctx context.Context, arg ClaimRetryableDeliveryAttemptsParams) ([]NotificationDeliveryAttempt, error)
	ClaimUnpublishedNotificationEvents(ctx context.Context, limit int32) ([]NotificationEvent, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationDeliveryAttempt, error)
	CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationEvent, error)
	CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error)
	DeadLetterNotificationEvent(ctx context.Context, arg DeadLetterNotificationEventParams) error
	DeliveryAttemptByID(ctx context.Context, id uuid.UUID) (NotificationDeliveryAttempt, error)
	DeliveryAttemptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (NotificationDeliveryAttempt, error)
	ListDeliveryAttemptsByUser(ctx context.Context, arg ListDeliveryAttemptsByUserParams) ([]NotificationDeliveryAttempt, error)
	ListNotificationPreferencesByUser(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error)
	ListNotificationTemplates(ctx context.Context, arg ListNotificationTemplatesParams) ([]NotificationTemplate, error)
	MarkDeliveryAttemptFailed(ctx context.Context, arg MarkDeliveryAttemptFailedParams) (NotificationDeliveryAttempt, error)
	MarkDeliveryAttemptSending(ctx context.Context, id uuid.UUID) (NotificationDeliveryAttempt, error)
	MarkDeliveryAttemptSent(ctx context.Context, arg MarkDeliveryAttemptSentParams) (NotificationDeliveryAttempt, error)
	MarkNotificationEventFailed(ctx context.Context, arg MarkNotificationEventFailedParams) error
	MarkNotificationEventPublished(ctx context.Context, id uuid.UUID) (int64, error)
	NotificationPreference(ctx context.Context, arg NotificationPreferenceParams) (NotificationPreference, error)
	NotificationTemplateByCode(ctx context.Context, arg NotificationTemplateByCodeParams) (NotificationTemplate, error)
	ProviderStatus(ctx context.Context, arg ProviderStatusParams) (NotificationProviderStatus, error)
	RevokeDeviceToken(ctx context.Context, tokenHash string) (int64, error)
	UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (NotificationTemplate, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error)
	UpsertProviderStatus(ctx context.Context, arg UpsertProviderStatusParams) (NotificationProviderStatus, error)
}

var _ Querier = (*Queries)(nil)
