// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/identity/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByPhoneRequest) Reset() {
	*x = GetUserByPhoneRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByPhoneRequest) ProtoMessage() {}

func (x *GetUserByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetUserByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetUserByUsernameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The handle without the leading @. Case-insensitive.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByAccountNumberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 10-digit Nablr handle (phone minus the leading zero).
	AccountNumber string `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByAccountNumberRequest) Reset() {
	*x = GetUserByAccountNumberRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByAccountNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByAccountNumberRequest) ProtoMessage() {}

func (x *GetUserByAccountNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByAccountNumberRequest.ProtoReflect.Descriptor instead.
func (*GetUserByAccountNumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByAccountNumberRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Role            string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PhoneVerified   bool                   `protobuf:"varint,6,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	PasswordSet     bool                   `protobuf:"varint,7,opt,name=password_set,json=passwordSet,proto3" json:"password_set,omitempty"`
	EmailVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	PhoneVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=phone_verified_at,json=phoneVerifiedAt,proto3" json:"phone_verified_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The @handle, without the leading @.
	NablrUsername string `protobuf:"bytes,11,opt,name=nablr_username,json=nablrUsername,proto3" json:"nablr_username,omitempty"`
	// The 10-digit handle other Nablr customers pay this person by. NOT the
	// funding account an external bank credits — that lives in transfers-svc.
	AccountNumber string `protobuf:"bytes,12,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Object-storage key of the user's profile image, if they uploaded one.
	AvatarUrl     string `protobuf:"bytes,13,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserResponse) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *GetUserResponse) GetPasswordSet() bool {
	if x != nil {
		return x.PasswordSet
	}
	return false
}

func (x *GetUserResponse) GetEmailVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return nil
}

func (x *GetUserResponse) GetPhoneVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhoneVerifiedAt
	}
	return nil
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserResponse) GetNablrUsername() string {
	if x != nil {
		return x.NablrUsername
	}
	return ""
}

func (x *GetUserResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetUserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetKYCProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCProfileRequest) Reset() {
	*x = GetKYCProfileRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCProfileRequest) ProtoMessage() {}

func (x *GetKYCProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCProfileRequest.ProtoReflect.Descriptor instead.
func (*GetKYCProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetKYCProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetKYCProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tier          int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneStatus   string                 `protobuf:"bytes,7,opt,name=phone_status,json=phoneStatus,proto3" json:"phone_status,omitempty"`
	BvnStatus     string                 `protobuf:"bytes,8,opt,name=bvn_status,json=bvnStatus,proto3" json:"bvn_status,omitempty"`
	NinStatus     string                 `protobuf:"bytes,9,opt,name=nin_status,json=ninStatus,proto3" json:"nin_status,omitempty"`
	Sanctioned    bool                   `protobuf:"varint,10,opt,name=sanctioned,proto3" json:"sanctioned,omitempty"`
	Pep           bool                   `protobuf:"varint,11,opt,name=pep,proto3" json:"pep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCProfileResponse) Reset() {
	*x = GetKYCProfileResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCProfileResponse) ProtoMessage() {}

func (x *GetKYCProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCProfileResponse.ProtoReflect.Descriptor instead.
func (*GetKYCProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetKYCProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetKYCProfileResponse) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *GetKYCProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetKYCProfileResponse) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *GetKYCProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetKYCProfileResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetKYCProfileResponse) GetPhoneStatus() string {
	if x != nil {
		return x.PhoneStatus
	}
	return ""
}

func (x *GetKYCProfileResponse) GetBvnStatus() string {
	if x != nil {
		return x.BvnStatus
	}
	return ""
}

func (x *GetKYCProfileResponse) GetNinStatus() string {
	if x != nil {
		return x.NinStatus
	}
	return ""
}

func (x *GetKYCProfileResponse) GetSanctioned() bool {
	if x != nil {
		return x.Sanctioned
	}
	return false
}

func (x *GetKYCProfileResponse) GetPep() bool {
	if x != nil {
		return x.Pep
	}
	return false
}

type ValidateKYCTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequiredTier  int32                  `protobuf:"varint,2,opt,name=required_tier,json=requiredTier,proto3" json:"required_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKYCTierRequest) Reset() {
	*x = ValidateKYCTierRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKYCTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKYCTierRequest) ProtoMessage() {}

func (x *ValidateKYCTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKYCTierRequest.ProtoReflect.Descriptor instead.
func (*ValidateKYCTierRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateKYCTierRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateKYCTierRequest) GetRequiredTier() int32 {
	if x != nil {
		return x.RequiredTier
	}
	return 0
}

type ValidateKYCTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	CurrentTier   int32                  `protobuf:"varint,2,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKYCTierResponse) Reset() {
	*x = ValidateKYCTierResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKYCTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKYCTierResponse) ProtoMessage() {}

func (x *ValidateKYCTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKYCTierResponse.ProtoReflect.Descriptor instead.
func (*ValidateKYCTierResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateKYCTierResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateKYCTierResponse) GetCurrentTier() int32 {
	if x != nil {
		return x.CurrentTier
	}
	return 0
}

func (x *ValidateKYCTierResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyPINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINRequest) Reset() {
	*x = VerifyPINRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINRequest) ProtoMessage() {}

func (x *VerifyPINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINRequest.ProtoReflect.Descriptor instead.
func (*VerifyPINRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyPINRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyPINRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type VerifyPINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINResponse) Reset() {
	*x = VerifyPINResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINResponse) ProtoMessage() {}

func (x *VerifyPINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINResponse.ProtoReflect.Descriptor instead.
func (*VerifyPINResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyPINResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyPINResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetPINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPINRequest) Reset() {
	*x = SetPINRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPINRequest) ProtoMessage() {}

func (x *SetPINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPINRequest.ProtoReflect.Descriptor instead.
func (*SetPINRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{11}
}

func (x *SetPINRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPINRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type SetPINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPINResponse) Reset() {
	*x = SetPINResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPINResponse) ProtoMessage() {}

func (x *SetPINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPINResponse.ProtoReflect.Descriptor instead.
func (*SetPINResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{12}
}

func (x *SetPINResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetPINResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	FcmToken      string                 `protobuf:"bytes,5,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterDeviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *RegisterDeviceRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDeviceRequest) Reset() {
	*x = ValidateDeviceRequest{}
	mi := &file_proto_identity_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeviceRequest) ProtoMessage() {}

func (x *ValidateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeviceRequest.ProtoReflect.Descriptor instead.
func (*ValidateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateDeviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ValidateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Trusted       bool                   `protobuf:"varint,2,opt,name=trusted,proto3" json:"trusted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDeviceResponse) Reset() {
	*x = ValidateDeviceResponse{}
	mi := &file_proto_identity_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeviceResponse) ProtoMessage() {}

func (x *ValidateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeviceResponse.ProtoReflect.Descriptor instead.
func (*ValidateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_identity_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateDeviceResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateDeviceResponse) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

func (x *ValidateDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_identity_identity_proto protoreflect.FileDescriptor

const file_proto_identity_identity_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/identity/identity.proto\x12\x11nabla.identity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x15GetUserByPhoneRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"F\n" +
	"\x1dGetUserByAccountNumberRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"\x91\x04\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0ephone_verified\x18\x06 \x01(\bR\rphoneVerified\x12!\n" +
	"\fpassword_set\x18\a \x01(\bR\vpasswordSet\x12F\n" +
	"\x11email_verified_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0femailVerifiedAt\x12F\n" +
	"\x11phone_verified_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fphoneVerifiedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0enablr_username\x18\v \x01(\tR\rnablrUsername\x12%\n" +
	"\x0eaccount_number\x18\f \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\r \x01(\tR\tavatarUrl\"/\n" +
	"\x14GetKYCProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd7\x02\n" +
	"\x15GetKYCProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\x05R\x04tier\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12!\n" +
	"\fphone_status\x18\a \x01(\tR\vphoneStatus\x12\x1d\n" +
	"\n" +
	"bvn_status\x18\b \x01(\tR\tbvnStatus\x12\x1d\n" +
	"\n" +
	"nin_status\x18\t \x01(\tR\tninStatus\x12\x1e\n" +
	"\n" +
	"sanctioned\x18\n" +
	" \x01(\bR\n" +
	"sanctioned\x12\x10\n" +
	"\x03pep\x18\v \x01(\bR\x03pep\"V\n" +
	"\x16ValidateKYCTierRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rrequired_tier\x18\x02 \x01(\x05R\frequiredTier\"l\n" +
	"\x17ValidateKYCTierResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12!\n" +
	"\fcurrent_tier\x18\x02 \x01(\x05R\vcurrentTier\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x10VerifyPINRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"C\n" +
	"\x11VerifyPINResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\rSetPINRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"D\n" +
	"\x0eSetPINResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xac\x01\n" +
	"\x15RegisterDeviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tfcm_token\x18\x05 \x01(\tR\bfcmToken\"L\n" +
	"\x16RegisterDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x15ValidateDeviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"b\n" +
	"\x16ValidateDeviceResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\atrusted\x18\x02 \x01(\bR\atrusted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xdc\a\n" +
	"\x0fIdentityService\x12P\n" +
	"\aGetUser\x12!.nabla.identity.v1.GetUserRequest\x1a\".nabla.identity.v1.GetUserResponse\x12^\n" +
	"\x0eGetUserByPhone\x12(.nabla.identity.v1.GetUserByPhoneRequest\x1a\".nabla.identity.v1.GetUserResponse\x12d\n" +
	"\x11GetUserByUsername\x12+.nabla.identity.v1.GetUserByUsernameRequest\x1a\".nabla.identity.v1.GetUserResponse\x12n\n" +
	"\x16GetUserByAccountNumber\x120.nabla.identity.v1.GetUserByAccountNumberRequest\x1a\".nabla.identity.v1.GetUserResponse\x12b\n" +
	"\rGetKYCProfile\x12'.nabla.identity.v1.GetKYCProfileRequest\x1a(.nabla.identity.v1.GetKYCProfileResponse\x12h\n" +
	"\x0fValidateKYCTier\x12).nabla.identity.v1.ValidateKYCTierRequest\x1a*.nabla.identity.v1.ValidateKYCTierResponse\x12V\n" +
	"\tVerifyPIN\x12#.nabla.identity.v1.VerifyPINRequest\x1a$.nabla.identity.v1.VerifyPINResponse\x12M\n" +
	"\x06SetPIN\x12 .nabla.identity.v1.SetPINRequest\x1a!.nabla.identity.v1.SetPINResponse\x12e\n" +
	"\x0eRegisterDevice\x12(.nabla.identity.v1.RegisterDeviceRequest\x1a).nabla.identity.v1.RegisterDeviceResponse\x12e\n" +
	"\x0eValidateDevice\x12(.nabla.identity.v1.ValidateDeviceRequest\x1a).nabla.identity.v1.ValidateDeviceResponseB,Z*nabla/identity-svc/proto/identity;identityb\x06proto3"

var (
	file_proto_identity_identity_proto_rawDescOnce sync.Once
	file_proto_identity_identity_proto_rawDescData []byte
)

func file_proto_identity_identity_proto_rawDescGZIP() []byte {
	file_proto_identity_identity_proto_rawDescOnce.Do(func() {
		file_proto_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_identity_identity_proto_rawDesc), len(file_proto_identity_identity_proto_rawDesc)))
	})
	return file_proto_identity_identity_proto_rawDescData
}

var file_proto_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_identity_identity_proto_goTypes = []any{
	(*GetUserRequest)(nil),                // 0: nabla.identity.v1.GetUserRequest
	(*GetUserByPhoneRequest)(nil),         // 1: nabla.identity.v1.GetUserByPhoneRequest
	(*GetUserByUsernameRequest)(nil),      // 2: nabla.identity.v1.GetUserByUsernameRequest
	(*GetUserByAccountNumberRequest)(nil), // 3: nabla.identity.v1.GetUserByAccountNumberRequest
	(*GetUserResponse)(nil),               // 4: nabla.identity.v1.GetUserResponse
	(*GetKYCProfileRequest)(nil),          // 5: nabla.identity.v1.GetKYCProfileRequest
	(*GetKYCProfileResponse)(nil),         // 6: nabla.identity.v1.GetKYCProfileResponse
	(*ValidateKYCTierRequest)(nil),        // 7: nabla.identity.v1.ValidateKYCTierRequest
	(*ValidateKYCTierResponse)(nil),       // 8: nabla.identity.v1.ValidateKYCTierResponse
	(*VerifyPINRequest)(nil),              // 9: nabla.identity.v1.VerifyPINRequest
	(*VerifyPINResponse)(nil),             // 10: nabla.identity.v1.VerifyPINResponse
	(*SetPINRequest)(nil),                 // 11: nabla.identity.v1.SetPINRequest
	(*SetPINResponse)(nil),                // 12: nabla.identity.v1.SetPINResponse
	(*RegisterDeviceRequest)(nil),         // 13: nabla.identity.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),        // 14: nabla.identity.v1.RegisterDeviceResponse
	(*ValidateDeviceRequest)(nil),         // 15: nabla.identity.v1.ValidateDeviceRequest
	(*ValidateDeviceResponse)(nil),        // 16: nabla.identity.v1.ValidateDeviceResponse
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
}
var file_proto_identity_identity_proto_depIdxs = []int32{
	17, // 0: nabla.identity.v1.GetUserResponse.email_verified_at:type_name -> google.protobuf.Timestamp
	17, // 1: nabla.identity.v1.GetUserResponse.phone_verified_at:type_name -> google.protobuf.Timestamp
	17, // 2: nabla.identity.v1.GetUserResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: nabla.identity.v1.IdentityService.GetUser:input_type -> nabla.identity.v1.GetUserRequest
	1,  // 4: nabla.identity.v1.IdentityService.GetUserByPhone:input_type -> nabla.identity.v1.GetUserByPhoneRequest
	2,  // 5: nabla.identity.v1.IdentityService.GetUserByUsername:input_type -> nabla.identity.v1.GetUserByUsernameRequest
	3,  // 6: nabla.identity.v1.IdentityService.GetUserByAccountNumber:input_type -> nabla.identity.v1.GetUserByAccountNumberRequest
	5,  // 7: nabla.identity.v1.IdentityService.GetKYCProfile:input_type -> nabla.identity.v1.GetKYCProfileRequest
	7,  // 8: nabla.identity.v1.IdentityService.ValidateKYCTier:input_type -> nabla.identity.v1.ValidateKYCTierRequest
	9,  // 9: nabla.identity.v1.IdentityService.VerifyPIN:input_type -> nabla.identity.v1.VerifyPINRequest
	11, // 10: nabla.identity.v1.IdentityService.SetPIN:input_type -> nabla.identity.v1.SetPINRequest
	13, // 11: nabla.identity.v1.IdentityService.RegisterDevice:input_type -> nabla.identity.v1.RegisterDeviceRequest
	15, // 12: nabla.identity.v1.IdentityService.ValidateDevice:input_type -> nabla.identity.v1.ValidateDeviceRequest
	4,  // 13: nabla.identity.v1.IdentityService.GetUser:output_type -> nabla.identity.v1.GetUserResponse
	4,  // 14: nabla.identity.v1.IdentityService.GetUserByPhone:output_type -> nabla.identity.v1.GetUserResponse
	4,  // 15: nabla.identity.v1.IdentityService.GetUserByUsername:output_type -> nabla.identity.v1.GetUserResponse
	4,  // 16: nabla.identity.v1.IdentityService.GetUserByAccountNumber:output_type -> nabla.identity.v1.GetUserResponse
	6,  // 17: nabla.identity.v1.IdentityService.GetKYCProfile:output_type -> nabla.identity.v1.GetKYCProfileResponse
	8,  // 18: nabla.identity.v1.IdentityService.ValidateKYCTier:output_type -> nabla.identity.v1.ValidateKYCTierResponse
	10, // 19: nabla.identity.v1.IdentityService.VerifyPIN:output_type -> nabla.identity.v1.VerifyPINResponse
	12, // 20: nabla.identity.v1.IdentityService.SetPIN:output_type -> nabla.identity.v1.SetPINResponse
	14, // 21: nabla.identity.v1.IdentityService.RegisterDevice:output_type -> nabla.identity.v1.RegisterDeviceResponse
	16, // 22: nabla.identity.v1.IdentityService.ValidateDevice:output_type -> nabla.identity.v1.ValidateDeviceResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_identity_identity_proto_init() }
func file_proto_identity_identity_proto_init() {
	if File_proto_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_identity_identity_proto_rawDesc), len(file_proto_identity_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_identity_identity_proto_goTypes,
		DependencyIndexes: file_proto_identity_identity_proto_depIdxs,
		MessageInfos:      file_proto_identity_identity_proto_msgTypes,
	}.Build()
	File_proto_identity_identity_proto = out.File
	file_proto_identity_identity_proto_goTypes = nil
	file_proto_identity_identity_proto_depIdxs = nil
}
